package com.example.demo.global.domain.model;

public class HbGun {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_gun.gunid
     *
     * @mbg.generated
     */
    private String gunid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_gun.gunmodel
     *
     * @mbg.generated
     */
    private String gunmodel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_gun.gunstate
     *
     * @mbg.generated
     */
    private String gunstate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_gun.bulletnum
     *
     * @mbg.generated
     */
    private Integer bulletnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_gun.orgid
     *
     * @mbg.generated
     */
    private String orgid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_gun.incharger
     *
     * @mbg.generated
     */
    private String incharger;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_gun.reserved1
     *
     * @mbg.generated
     */
    private String reserved1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_gun.reserved2
     *
     * @mbg.generated
     */
    private String reserved2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_gun.reserved3
     *
     * @mbg.generated
     */
    private String reserved3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_gun.reserved4
     *
     * @mbg.generated
     */
    private String reserved4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_gun.reserved5
     *
     * @mbg.generated
     */
    private String reserved5;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_gun.gunid
     *
     * @return the value of hb_gun.gunid
     *
     * @mbg.generated
     */
    public String getGunid() {
        return gunid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_gun.gunid
     *
     * @param gunid the value for hb_gun.gunid
     *
     * @mbg.generated
     */
    public void setGunid(String gunid) {
        this.gunid = gunid == null ? null : gunid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_gun.gunmodel
     *
     * @return the value of hb_gun.gunmodel
     *
     * @mbg.generated
     */
    public String getGunmodel() {
        return gunmodel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_gun.gunmodel
     *
     * @param gunmodel the value for hb_gun.gunmodel
     *
     * @mbg.generated
     */
    public void setGunmodel(String gunmodel) {
        this.gunmodel = gunmodel == null ? null : gunmodel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_gun.gunstate
     *
     * @return the value of hb_gun.gunstate
     *
     * @mbg.generated
     */
    public String getGunstate() {
        return gunstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_gun.gunstate
     *
     * @param gunstate the value for hb_gun.gunstate
     *
     * @mbg.generated
     */
    public void setGunstate(String gunstate) {
        this.gunstate = gunstate == null ? null : gunstate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_gun.bulletnum
     *
     * @return the value of hb_gun.bulletnum
     *
     * @mbg.generated
     */
    public Integer getBulletnum() {
        return bulletnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_gun.bulletnum
     *
     * @param bulletnum the value for hb_gun.bulletnum
     *
     * @mbg.generated
     */
    public void setBulletnum(Integer bulletnum) {
        this.bulletnum = bulletnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_gun.orgid
     *
     * @return the value of hb_gun.orgid
     *
     * @mbg.generated
     */
    public String getOrgid() {
        return orgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_gun.orgid
     *
     * @param orgid the value for hb_gun.orgid
     *
     * @mbg.generated
     */
    public void setOrgid(String orgid) {
        this.orgid = orgid == null ? null : orgid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_gun.incharger
     *
     * @return the value of hb_gun.incharger
     *
     * @mbg.generated
     */
    public String getIncharger() {
        return incharger;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_gun.incharger
     *
     * @param incharger the value for hb_gun.incharger
     *
     * @mbg.generated
     */
    public void setIncharger(String incharger) {
        this.incharger = incharger == null ? null : incharger.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_gun.reserved1
     *
     * @return the value of hb_gun.reserved1
     *
     * @mbg.generated
     */
    public String getReserved1() {
        return reserved1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_gun.reserved1
     *
     * @param reserved1 the value for hb_gun.reserved1
     *
     * @mbg.generated
     */
    public void setReserved1(String reserved1) {
        this.reserved1 = reserved1 == null ? null : reserved1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_gun.reserved2
     *
     * @return the value of hb_gun.reserved2
     *
     * @mbg.generated
     */
    public String getReserved2() {
        return reserved2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_gun.reserved2
     *
     * @param reserved2 the value for hb_gun.reserved2
     *
     * @mbg.generated
     */
    public void setReserved2(String reserved2) {
        this.reserved2 = reserved2 == null ? null : reserved2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_gun.reserved3
     *
     * @return the value of hb_gun.reserved3
     *
     * @mbg.generated
     */
    public String getReserved3() {
        return reserved3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_gun.reserved3
     *
     * @param reserved3 the value for hb_gun.reserved3
     *
     * @mbg.generated
     */
    public void setReserved3(String reserved3) {
        this.reserved3 = reserved3 == null ? null : reserved3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_gun.reserved4
     *
     * @return the value of hb_gun.reserved4
     *
     * @mbg.generated
     */
    public String getReserved4() {
        return reserved4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_gun.reserved4
     *
     * @param reserved4 the value for hb_gun.reserved4
     *
     * @mbg.generated
     */
    public void setReserved4(String reserved4) {
        this.reserved4 = reserved4 == null ? null : reserved4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_gun.reserved5
     *
     * @return the value of hb_gun.reserved5
     *
     * @mbg.generated
     */
    public String getReserved5() {
        return reserved5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_gun.reserved5
     *
     * @param reserved5 the value for hb_gun.reserved5
     *
     * @mbg.generated
     */
    public void setReserved5(String reserved5) {
        this.reserved5 = reserved5 == null ? null : reserved5.trim();
    }
}