package com.example.demo.global.domain.model;

import java.util.Date;

public class HbIntercomInoutWarning {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_intercom_inout_warning.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_intercom_inout_warning.intercomno
     *
     * @mbg.generated
     */
    private String intercomno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_intercom_inout_warning.vehicleid
     *
     * @mbg.generated
     */
    private String vehicleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_intercom_inout_warning.orgid
     *
     * @mbg.generated
     */
    private String orgid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_intercom_inout_warning.orgname
     *
     * @mbg.generated
     */
    private String orgname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_intercom_inout_warning.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_intercom_inout_warning.createidtime
     *
     * @mbg.generated
     */
    private Date createidtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_intercom_inout_warning.dealstate
     *
     * @mbg.generated
     */
    private String dealstate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_intercom_inout_warning.dealuserid
     *
     * @mbg.generated
     */
    private String dealuserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_intercom_inout_warning.comment
     *
     * @mbg.generated
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_intercom_inout_warning.dealtime
     *
     * @mbg.generated
     */
    private Date dealtime;
    /**
     * 对讲机出入库id
     */
    private String intercominoutid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_intercom_inout_warning.id
     *
     * @return the value of hb_intercom_inout_warning.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_intercom_inout_warning.id
     *
     * @param id the value for hb_intercom_inout_warning.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_intercom_inout_warning.intercomno
     *
     * @return the value of hb_intercom_inout_warning.intercomno
     *
     * @mbg.generated
     */
    public String getIntercomno() {
        return intercomno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_intercom_inout_warning.intercomno
     *
     * @param intercomno the value for hb_intercom_inout_warning.intercomno
     *
     * @mbg.generated
     */
    public void setIntercomno(String intercomno) {
        this.intercomno = intercomno == null ? null : intercomno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_intercom_inout_warning.vehicleid
     *
     * @return the value of hb_intercom_inout_warning.vehicleid
     *
     * @mbg.generated
     */
    public String getVehicleid() {
        return vehicleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_intercom_inout_warning.vehicleid
     *
     * @param vehicleid the value for hb_intercom_inout_warning.vehicleid
     *
     * @mbg.generated
     */
    public void setVehicleid(String vehicleid) {
        this.vehicleid = vehicleid == null ? null : vehicleid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_intercom_inout_warning.orgid
     *
     * @return the value of hb_intercom_inout_warning.orgid
     *
     * @mbg.generated
     */
    public String getOrgid() {
        return orgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_intercom_inout_warning.orgid
     *
     * @param orgid the value for hb_intercom_inout_warning.orgid
     *
     * @mbg.generated
     */
    public void setOrgid(String orgid) {
        this.orgid = orgid == null ? null : orgid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_intercom_inout_warning.orgname
     *
     * @return the value of hb_intercom_inout_warning.orgname
     *
     * @mbg.generated
     */
    public String getOrgname() {
        return orgname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_intercom_inout_warning.orgname
     *
     * @param orgname the value for hb_intercom_inout_warning.orgname
     *
     * @mbg.generated
     */
    public void setOrgname(String orgname) {
        this.orgname = orgname == null ? null : orgname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_intercom_inout_warning.type
     *
     * @return the value of hb_intercom_inout_warning.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_intercom_inout_warning.type
     *
     * @param type the value for hb_intercom_inout_warning.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_intercom_inout_warning.createidtime
     *
     * @return the value of hb_intercom_inout_warning.createidtime
     *
     * @mbg.generated
     */
    public Date getCreateidtime() {
        return createidtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_intercom_inout_warning.createidtime
     *
     * @param createidtime the value for hb_intercom_inout_warning.createidtime
     *
     * @mbg.generated
     */
    public void setCreateidtime(Date createidtime) {
        this.createidtime = createidtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_intercom_inout_warning.dealstate
     *
     * @return the value of hb_intercom_inout_warning.dealstate
     *
     * @mbg.generated
     */
    public String getDealstate() {
        return dealstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_intercom_inout_warning.dealstate
     *
     * @param dealstate the value for hb_intercom_inout_warning.dealstate
     *
     * @mbg.generated
     */
    public void setDealstate(String dealstate) {
        this.dealstate = dealstate == null ? null : dealstate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_intercom_inout_warning.dealuserid
     *
     * @return the value of hb_intercom_inout_warning.dealuserid
     *
     * @mbg.generated
     */
    public String getDealuserid() {
        return dealuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_intercom_inout_warning.dealuserid
     *
     * @param dealuserid the value for hb_intercom_inout_warning.dealuserid
     *
     * @mbg.generated
     */
    public void setDealuserid(String dealuserid) {
        this.dealuserid = dealuserid == null ? null : dealuserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_intercom_inout_warning.comment
     *
     * @return the value of hb_intercom_inout_warning.comment
     *
     * @mbg.generated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_intercom_inout_warning.comment
     *
     * @param comment the value for hb_intercom_inout_warning.comment
     *
     * @mbg.generated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_intercom_inout_warning.dealtime
     *
     * @return the value of hb_intercom_inout_warning.dealtime
     *
     * @mbg.generated
     */
    public Date getDealtime() {
        return dealtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_intercom_inout_warning.dealtime
     *
     * @param dealtime the value for hb_intercom_inout_warning.dealtime
     *
     * @mbg.generated
     */
    public void setDealtime(Date dealtime) {
        this.dealtime = dealtime;
    }

    public String getIntercominoutid() {
        return intercominoutid;
    }

    public void setIntercominoutid(String intercominoutid) {
        this.intercominoutid = intercominoutid;
    }

    @Override
    public String toString() {
        return "HbIntercomInoutWarning{" + "id='" + id + '\'' + ", intercomno='" + intercomno + '\'' + ", vehicleid='" + vehicleid + '\'' + ", orgid='" + orgid + '\'' + ", orgname='" + orgname + '\'' + ", type='" + type + '\'' + ", createidtime=" + createidtime + ", dealstate='" + dealstate + '\'' + ", dealuserid='" + dealuserid + '\'' + ", comment='" + comment + '\'' + ", dealtime=" + dealtime + ", intercominoutid='" + intercominoutid + '\'' + '}';
    }
}