package com.example.demo.global.domain.model;

public class HbIntercom {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_intercom.intercomid
     *
     * @mbg.generated
     */
    private String intercomid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_intercom.iccid
     *
     * @mbg.generated
     */
    private String iccid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_intercom.imei
     *
     * @mbg.generated
     */
    private String imei;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_intercom.intercom_vehicleid
     *
     * @mbg.generated
     */
    private String intercomVehicleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_intercom.intercomstate
     *
     * @mbg.generated
     */
    private String intercomstate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_intercom.orgid
     *
     * @mbg.generated
     */
    private String orgid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_intercom.orgname
     *
     * @mbg.generated
     */
    private String orgname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_intercom.reserved1
     *
     * @mbg.generated
     */
    private String reserved1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_intercom.reserved2
     *
     * @mbg.generated
     */
    private String reserved2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_intercom.reserved3
     *
     * @mbg.generated
     */
    private String reserved3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_intercom.reserved4
     *
     * @mbg.generated
     */
    private String reserved4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_intercom.reserved5
     *
     * @mbg.generated
     */
    private String reserved5;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_intercom.intercomid
     *
     * @return the value of hb_intercom.intercomid
     *
     * @mbg.generated
     */
    public String getIntercomid() {
        return intercomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_intercom.intercomid
     *
     * @param intercomid the value for hb_intercom.intercomid
     *
     * @mbg.generated
     */
    public void setIntercomid(String intercomid) {
        this.intercomid = intercomid == null ? null : intercomid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_intercom.iccid
     *
     * @return the value of hb_intercom.iccid
     *
     * @mbg.generated
     */
    public String getIccid() {
        return iccid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_intercom.iccid
     *
     * @param iccid the value for hb_intercom.iccid
     *
     * @mbg.generated
     */
    public void setIccid(String iccid) {
        this.iccid = iccid == null ? null : iccid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_intercom.imei
     *
     * @return the value of hb_intercom.imei
     *
     * @mbg.generated
     */
    public String getImei() {
        return imei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_intercom.imei
     *
     * @param imei the value for hb_intercom.imei
     *
     * @mbg.generated
     */
    public void setImei(String imei) {
        this.imei = imei == null ? null : imei.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_intercom.intercom_vehicleid
     *
     * @return the value of hb_intercom.intercom_vehicleid
     *
     * @mbg.generated
     */
    public String getIntercomVehicleid() {
        return intercomVehicleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_intercom.intercom_vehicleid
     *
     * @param intercomVehicleid the value for hb_intercom.intercom_vehicleid
     *
     * @mbg.generated
     */
    public void setIntercomVehicleid(String intercomVehicleid) {
        this.intercomVehicleid = intercomVehicleid == null ? null : intercomVehicleid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_intercom.intercomstate
     *
     * @return the value of hb_intercom.intercomstate
     *
     * @mbg.generated
     */
    public String getIntercomstate() {
        return intercomstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_intercom.intercomstate
     *
     * @param intercomstate the value for hb_intercom.intercomstate
     *
     * @mbg.generated
     */
    public void setIntercomstate(String intercomstate) {
        this.intercomstate = intercomstate == null ? null : intercomstate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_intercom.orgid
     *
     * @return the value of hb_intercom.orgid
     *
     * @mbg.generated
     */
    public String getOrgid() {
        return orgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_intercom.orgid
     *
     * @param orgid the value for hb_intercom.orgid
     *
     * @mbg.generated
     */
    public void setOrgid(String orgid) {
        this.orgid = orgid == null ? null : orgid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_intercom.orgname
     *
     * @return the value of hb_intercom.orgname
     *
     * @mbg.generated
     */
    public String getOrgname() {
        return orgname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_intercom.orgname
     *
     * @param orgname the value for hb_intercom.orgname
     *
     * @mbg.generated
     */
    public void setOrgname(String orgname) {
        this.orgname = orgname == null ? null : orgname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_intercom.reserved1
     *
     * @return the value of hb_intercom.reserved1
     *
     * @mbg.generated
     */
    public String getReserved1() {
        return reserved1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_intercom.reserved1
     *
     * @param reserved1 the value for hb_intercom.reserved1
     *
     * @mbg.generated
     */
    public void setReserved1(String reserved1) {
        this.reserved1 = reserved1 == null ? null : reserved1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_intercom.reserved2
     *
     * @return the value of hb_intercom.reserved2
     *
     * @mbg.generated
     */
    public String getReserved2() {
        return reserved2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_intercom.reserved2
     *
     * @param reserved2 the value for hb_intercom.reserved2
     *
     * @mbg.generated
     */
    public void setReserved2(String reserved2) {
        this.reserved2 = reserved2 == null ? null : reserved2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_intercom.reserved3
     *
     * @return the value of hb_intercom.reserved3
     *
     * @mbg.generated
     */
    public String getReserved3() {
        return reserved3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_intercom.reserved3
     *
     * @param reserved3 the value for hb_intercom.reserved3
     *
     * @mbg.generated
     */
    public void setReserved3(String reserved3) {
        this.reserved3 = reserved3 == null ? null : reserved3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_intercom.reserved4
     *
     * @return the value of hb_intercom.reserved4
     *
     * @mbg.generated
     */
    public String getReserved4() {
        return reserved4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_intercom.reserved4
     *
     * @param reserved4 the value for hb_intercom.reserved4
     *
     * @mbg.generated
     */
    public void setReserved4(String reserved4) {
        this.reserved4 = reserved4 == null ? null : reserved4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_intercom.reserved5
     *
     * @return the value of hb_intercom.reserved5
     *
     * @mbg.generated
     */
    public String getReserved5() {
        return reserved5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_intercom.reserved5
     *
     * @param reserved5 the value for hb_intercom.reserved5
     *
     * @mbg.generated
     */
    public void setReserved5(String reserved5) {
        this.reserved5 = reserved5 == null ? null : reserved5.trim();
    }
}