package com.example.demo.global.domain.model;

import java.util.Date;

public class HbLicenseReminding {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_license_reminding.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_license_reminding.licenseid
     *
     * @mbg.generated
     */
    private String licenseid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_license_reminding.userid
     *
     * @mbg.generated
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_license_reminding.username
     *
     * @mbg.generated
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_license_reminding.orgid
     *
     * @mbg.generated
     */
    private String orgid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_license_reminding.orgname
     *
     * @mbg.generated
     */
    private String orgname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_license_reminding.expiretime
     *
     * @mbg.generated
     */
    private Date expiretime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_license_reminding.createidtime
     *
     * @mbg.generated
     */
    private Date createidtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_license_reminding.dealstate
     *
     * @mbg.generated
     */
    private String dealstate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_license_reminding.dealuserid
     *
     * @mbg.generated
     */
    private String dealuserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_license_reminding.dealtime
     *
     * @mbg.generated
     */
    private Date dealtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_license_reminding.id
     *
     * @return the value of hb_license_reminding.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_license_reminding.id
     *
     * @param id the value for hb_license_reminding.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_license_reminding.licenseid
     *
     * @return the value of hb_license_reminding.licenseid
     *
     * @mbg.generated
     */
    public String getLicenseid() {
        return licenseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_license_reminding.licenseid
     *
     * @param licenseid the value for hb_license_reminding.licenseid
     *
     * @mbg.generated
     */
    public void setLicenseid(String licenseid) {
        this.licenseid = licenseid == null ? null : licenseid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_license_reminding.userid
     *
     * @return the value of hb_license_reminding.userid
     *
     * @mbg.generated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_license_reminding.userid
     *
     * @param userid the value for hb_license_reminding.userid
     *
     * @mbg.generated
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_license_reminding.username
     *
     * @return the value of hb_license_reminding.username
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_license_reminding.username
     *
     * @param username the value for hb_license_reminding.username
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_license_reminding.orgid
     *
     * @return the value of hb_license_reminding.orgid
     *
     * @mbg.generated
     */
    public String getOrgid() {
        return orgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_license_reminding.orgid
     *
     * @param orgid the value for hb_license_reminding.orgid
     *
     * @mbg.generated
     */
    public void setOrgid(String orgid) {
        this.orgid = orgid == null ? null : orgid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_license_reminding.orgname
     *
     * @return the value of hb_license_reminding.orgname
     *
     * @mbg.generated
     */
    public String getOrgname() {
        return orgname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_license_reminding.orgname
     *
     * @param orgname the value for hb_license_reminding.orgname
     *
     * @mbg.generated
     */
    public void setOrgname(String orgname) {
        this.orgname = orgname == null ? null : orgname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_license_reminding.expiretime
     *
     * @return the value of hb_license_reminding.expiretime
     *
     * @mbg.generated
     */
    public Date getExpiretime() {
        return expiretime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_license_reminding.expiretime
     *
     * @param expiretime the value for hb_license_reminding.expiretime
     *
     * @mbg.generated
     */
    public void setExpiretime(Date expiretime) {
        this.expiretime = expiretime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_license_reminding.createidtime
     *
     * @return the value of hb_license_reminding.createidtime
     *
     * @mbg.generated
     */
    public Date getCreateidtime() {
        return createidtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_license_reminding.createidtime
     *
     * @param createidtime the value for hb_license_reminding.createidtime
     *
     * @mbg.generated
     */
    public void setCreateidtime(Date createidtime) {
        this.createidtime = createidtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_license_reminding.dealstate
     *
     * @return the value of hb_license_reminding.dealstate
     *
     * @mbg.generated
     */
    public String getDealstate() {
        return dealstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_license_reminding.dealstate
     *
     * @param dealstate the value for hb_license_reminding.dealstate
     *
     * @mbg.generated
     */
    public void setDealstate(String dealstate) {
        this.dealstate = dealstate == null ? null : dealstate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_license_reminding.dealuserid
     *
     * @return the value of hb_license_reminding.dealuserid
     *
     * @mbg.generated
     */
    public String getDealuserid() {
        return dealuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_license_reminding.dealuserid
     *
     * @param dealuserid the value for hb_license_reminding.dealuserid
     *
     * @mbg.generated
     */
    public void setDealuserid(String dealuserid) {
        this.dealuserid = dealuserid == null ? null : dealuserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_license_reminding.dealtime
     *
     * @return the value of hb_license_reminding.dealtime
     *
     * @mbg.generated
     */
    public Date getDealtime() {
        return dealtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_license_reminding.dealtime
     *
     * @param dealtime the value for hb_license_reminding.dealtime
     *
     * @mbg.generated
     */
    public void setDealtime(Date dealtime) {
        this.dealtime = dealtime;
    }
}