package com.example.demo.global.domain.model;

public class HbPatrolcontent {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_patrolcontent.patrolplanno
     *
     * @mbg.generated
     */
    private String patrolplanno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_patrolcontent.patrolplaceid
     *
     * @mbg.generated
     */
    private String patrolplaceid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_patrolcontent.patrolno
     *
     * @mbg.generated
     */
    private Integer patrolno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_patrolcontent.reserved1
     *
     * @mbg.generated
     */
    private String reserved1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_patrolcontent.reserved2
     *
     * @mbg.generated
     */
    private String reserved2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_patrolcontent.reserved3
     *
     * @mbg.generated
     */
    private String reserved3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_patrolcontent.reserved4
     *
     * @mbg.generated
     */
    private String reserved4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_patrolcontent.reserved5
     *
     * @mbg.generated
     */
    private String reserved5;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_patrolcontent.patrolplanno
     *
     * @return the value of hb_patrolcontent.patrolplanno
     *
     * @mbg.generated
     */
    public String getPatrolplanno() {
        return patrolplanno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_patrolcontent.patrolplanno
     *
     * @param patrolplanno the value for hb_patrolcontent.patrolplanno
     *
     * @mbg.generated
     */
    public void setPatrolplanno(String patrolplanno) {
        this.patrolplanno = patrolplanno == null ? null : patrolplanno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_patrolcontent.patrolplaceid
     *
     * @return the value of hb_patrolcontent.patrolplaceid
     *
     * @mbg.generated
     */
    public String getPatrolplaceid() {
        return patrolplaceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_patrolcontent.patrolplaceid
     *
     * @param patrolplaceid the value for hb_patrolcontent.patrolplaceid
     *
     * @mbg.generated
     */
    public void setPatrolplaceid(String patrolplaceid) {
        this.patrolplaceid = patrolplaceid == null ? null : patrolplaceid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_patrolcontent.patrolno
     *
     * @return the value of hb_patrolcontent.patrolno
     *
     * @mbg.generated
     */
    public Integer getPatrolno() {
        return patrolno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_patrolcontent.patrolno
     *
     * @param patrolno the value for hb_patrolcontent.patrolno
     *
     * @mbg.generated
     */
    public void setPatrolno(Integer patrolno) {
        this.patrolno = patrolno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_patrolcontent.reserved1
     *
     * @return the value of hb_patrolcontent.reserved1
     *
     * @mbg.generated
     */
    public String getReserved1() {
        return reserved1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_patrolcontent.reserved1
     *
     * @param reserved1 the value for hb_patrolcontent.reserved1
     *
     * @mbg.generated
     */
    public void setReserved1(String reserved1) {
        this.reserved1 = reserved1 == null ? null : reserved1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_patrolcontent.reserved2
     *
     * @return the value of hb_patrolcontent.reserved2
     *
     * @mbg.generated
     */
    public String getReserved2() {
        return reserved2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_patrolcontent.reserved2
     *
     * @param reserved2 the value for hb_patrolcontent.reserved2
     *
     * @mbg.generated
     */
    public void setReserved2(String reserved2) {
        this.reserved2 = reserved2 == null ? null : reserved2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_patrolcontent.reserved3
     *
     * @return the value of hb_patrolcontent.reserved3
     *
     * @mbg.generated
     */
    public String getReserved3() {
        return reserved3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_patrolcontent.reserved3
     *
     * @param reserved3 the value for hb_patrolcontent.reserved3
     *
     * @mbg.generated
     */
    public void setReserved3(String reserved3) {
        this.reserved3 = reserved3 == null ? null : reserved3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_patrolcontent.reserved4
     *
     * @return the value of hb_patrolcontent.reserved4
     *
     * @mbg.generated
     */
    public String getReserved4() {
        return reserved4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_patrolcontent.reserved4
     *
     * @param reserved4 the value for hb_patrolcontent.reserved4
     *
     * @mbg.generated
     */
    public void setReserved4(String reserved4) {
        this.reserved4 = reserved4 == null ? null : reserved4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_patrolcontent.reserved5
     *
     * @return the value of hb_patrolcontent.reserved5
     *
     * @mbg.generated
     */
    public String getReserved5() {
        return reserved5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_patrolcontent.reserved5
     *
     * @param reserved5 the value for hb_patrolcontent.reserved5
     *
     * @mbg.generated
     */
    public void setReserved5(String reserved5) {
        this.reserved5 = reserved5 == null ? null : reserved5.trim();
    }
}