package com.example.demo.global.domain.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class HbPatroltaskExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hb_patroltask
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hb_patroltask
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hb_patroltask
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_patroltask
     *
     * @mbg.generated
     */
    public HbPatroltaskExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_patroltask
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_patroltask
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_patroltask
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_patroltask
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_patroltask
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_patroltask
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_patroltask
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_patroltask
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_patroltask
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_patroltask
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hb_patroltask
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andPatroltasknoIsNull() {
            addCriterion("patroltaskno is null");
            return (Criteria) this;
        }

        public Criteria andPatroltasknoIsNotNull() {
            addCriterion("patroltaskno is not null");
            return (Criteria) this;
        }

        public Criteria andPatroltasknoEqualTo(String value) {
            addCriterion("patroltaskno =", value, "patroltaskno");
            return (Criteria) this;
        }

        public Criteria andPatroltasknoNotEqualTo(String value) {
            addCriterion("patroltaskno <>", value, "patroltaskno");
            return (Criteria) this;
        }

        public Criteria andPatroltasknoGreaterThan(String value) {
            addCriterion("patroltaskno >", value, "patroltaskno");
            return (Criteria) this;
        }

        public Criteria andPatroltasknoGreaterThanOrEqualTo(String value) {
            addCriterion("patroltaskno >=", value, "patroltaskno");
            return (Criteria) this;
        }

        public Criteria andPatroltasknoLessThan(String value) {
            addCriterion("patroltaskno <", value, "patroltaskno");
            return (Criteria) this;
        }

        public Criteria andPatroltasknoLessThanOrEqualTo(String value) {
            addCriterion("patroltaskno <=", value, "patroltaskno");
            return (Criteria) this;
        }

        public Criteria andPatroltasknoLike(String value) {
            addCriterion("patroltaskno like", value, "patroltaskno");
            return (Criteria) this;
        }

        public Criteria andPatroltasknoNotLike(String value) {
            addCriterion("patroltaskno not like", value, "patroltaskno");
            return (Criteria) this;
        }

        public Criteria andPatroltasknoIn(List<String> values) {
            addCriterion("patroltaskno in", values, "patroltaskno");
            return (Criteria) this;
        }

        public Criteria andPatroltasknoNotIn(List<String> values) {
            addCriterion("patroltaskno not in", values, "patroltaskno");
            return (Criteria) this;
        }

        public Criteria andPatroltasknoBetween(String value1, String value2) {
            addCriterion("patroltaskno between", value1, value2, "patroltaskno");
            return (Criteria) this;
        }

        public Criteria andPatroltasknoNotBetween(String value1, String value2) {
            addCriterion("patroltaskno not between", value1, value2, "patroltaskno");
            return (Criteria) this;
        }

        public Criteria andPatrolplannoIsNull() {
            addCriterion("patrolplanno is null");
            return (Criteria) this;
        }

        public Criteria andPatrolplannoIsNotNull() {
            addCriterion("patrolplanno is not null");
            return (Criteria) this;
        }

        public Criteria andPatrolplannoEqualTo(String value) {
            addCriterion("patrolplanno =", value, "patrolplanno");
            return (Criteria) this;
        }

        public Criteria andPatrolplannoNotEqualTo(String value) {
            addCriterion("patrolplanno <>", value, "patrolplanno");
            return (Criteria) this;
        }

        public Criteria andPatrolplannoGreaterThan(String value) {
            addCriterion("patrolplanno >", value, "patrolplanno");
            return (Criteria) this;
        }

        public Criteria andPatrolplannoGreaterThanOrEqualTo(String value) {
            addCriterion("patrolplanno >=", value, "patrolplanno");
            return (Criteria) this;
        }

        public Criteria andPatrolplannoLessThan(String value) {
            addCriterion("patrolplanno <", value, "patrolplanno");
            return (Criteria) this;
        }

        public Criteria andPatrolplannoLessThanOrEqualTo(String value) {
            addCriterion("patrolplanno <=", value, "patrolplanno");
            return (Criteria) this;
        }

        public Criteria andPatrolplannoLike(String value) {
            addCriterion("patrolplanno like", value, "patrolplanno");
            return (Criteria) this;
        }

        public Criteria andPatrolplannoNotLike(String value) {
            addCriterion("patrolplanno not like", value, "patrolplanno");
            return (Criteria) this;
        }

        public Criteria andPatrolplannoIn(List<String> values) {
            addCriterion("patrolplanno in", values, "patrolplanno");
            return (Criteria) this;
        }

        public Criteria andPatrolplannoNotIn(List<String> values) {
            addCriterion("patrolplanno not in", values, "patrolplanno");
            return (Criteria) this;
        }

        public Criteria andPatrolplannoBetween(String value1, String value2) {
            addCriterion("patrolplanno between", value1, value2, "patrolplanno");
            return (Criteria) this;
        }

        public Criteria andPatrolplannoNotBetween(String value1, String value2) {
            addCriterion("patrolplanno not between", value1, value2, "patrolplanno");
            return (Criteria) this;
        }

        public Criteria andOrgidIsNull() {
            addCriterion("orgid is null");
            return (Criteria) this;
        }

        public Criteria andOrgidIsNotNull() {
            addCriterion("orgid is not null");
            return (Criteria) this;
        }

        public Criteria andOrgidEqualTo(String value) {
            addCriterion("orgid =", value, "orgid");
            return (Criteria) this;
        }

        public Criteria andOrgidNotEqualTo(String value) {
            addCriterion("orgid <>", value, "orgid");
            return (Criteria) this;
        }

        public Criteria andOrgidGreaterThan(String value) {
            addCriterion("orgid >", value, "orgid");
            return (Criteria) this;
        }

        public Criteria andOrgidGreaterThanOrEqualTo(String value) {
            addCriterion("orgid >=", value, "orgid");
            return (Criteria) this;
        }

        public Criteria andOrgidLessThan(String value) {
            addCriterion("orgid <", value, "orgid");
            return (Criteria) this;
        }

        public Criteria andOrgidLessThanOrEqualTo(String value) {
            addCriterion("orgid <=", value, "orgid");
            return (Criteria) this;
        }

        public Criteria andOrgidLike(String value) {
            addCriterion("orgid like", value, "orgid");
            return (Criteria) this;
        }

        public Criteria andOrgidNotLike(String value) {
            addCriterion("orgid not like", value, "orgid");
            return (Criteria) this;
        }

        public Criteria andOrgidIn(List<String> values) {
            addCriterion("orgid in", values, "orgid");
            return (Criteria) this;
        }

        public Criteria andOrgidNotIn(List<String> values) {
            addCriterion("orgid not in", values, "orgid");
            return (Criteria) this;
        }

        public Criteria andOrgidBetween(String value1, String value2) {
            addCriterion("orgid between", value1, value2, "orgid");
            return (Criteria) this;
        }

        public Criteria andOrgidNotBetween(String value1, String value2) {
            addCriterion("orgid not between", value1, value2, "orgid");
            return (Criteria) this;
        }

        public Criteria andOrgnameIsNull() {
            addCriterion("orgname is null");
            return (Criteria) this;
        }

        public Criteria andOrgnameIsNotNull() {
            addCriterion("orgname is not null");
            return (Criteria) this;
        }

        public Criteria andOrgnameEqualTo(String value) {
            addCriterion("orgname =", value, "orgname");
            return (Criteria) this;
        }

        public Criteria andOrgnameNotEqualTo(String value) {
            addCriterion("orgname <>", value, "orgname");
            return (Criteria) this;
        }

        public Criteria andOrgnameGreaterThan(String value) {
            addCriterion("orgname >", value, "orgname");
            return (Criteria) this;
        }

        public Criteria andOrgnameGreaterThanOrEqualTo(String value) {
            addCriterion("orgname >=", value, "orgname");
            return (Criteria) this;
        }

        public Criteria andOrgnameLessThan(String value) {
            addCriterion("orgname <", value, "orgname");
            return (Criteria) this;
        }

        public Criteria andOrgnameLessThanOrEqualTo(String value) {
            addCriterion("orgname <=", value, "orgname");
            return (Criteria) this;
        }

        public Criteria andOrgnameLike(String value) {
            addCriterion("orgname like", value, "orgname");
            return (Criteria) this;
        }

        public Criteria andOrgnameNotLike(String value) {
            addCriterion("orgname not like", value, "orgname");
            return (Criteria) this;
        }

        public Criteria andOrgnameIn(List<String> values) {
            addCriterion("orgname in", values, "orgname");
            return (Criteria) this;
        }

        public Criteria andOrgnameNotIn(List<String> values) {
            addCriterion("orgname not in", values, "orgname");
            return (Criteria) this;
        }

        public Criteria andOrgnameBetween(String value1, String value2) {
            addCriterion("orgname between", value1, value2, "orgname");
            return (Criteria) this;
        }

        public Criteria andOrgnameNotBetween(String value1, String value2) {
            addCriterion("orgname not between", value1, value2, "orgname");
            return (Criteria) this;
        }

        public Criteria andStarttimeIsNull() {
            addCriterion("starttime is null");
            return (Criteria) this;
        }

        public Criteria andStarttimeIsNotNull() {
            addCriterion("starttime is not null");
            return (Criteria) this;
        }

        public Criteria andStarttimeEqualTo(Date value) {
            addCriterion("starttime =", value, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeNotEqualTo(Date value) {
            addCriterion("starttime <>", value, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeGreaterThan(Date value) {
            addCriterion("starttime >", value, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeGreaterThanOrEqualTo(Date value) {
            addCriterion("starttime >=", value, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeLessThan(Date value) {
            addCriterion("starttime <", value, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeLessThanOrEqualTo(Date value) {
            addCriterion("starttime <=", value, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeIn(List<Date> values) {
            addCriterion("starttime in", values, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeNotIn(List<Date> values) {
            addCriterion("starttime not in", values, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeBetween(Date value1, Date value2) {
            addCriterion("starttime between", value1, value2, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeNotBetween(Date value1, Date value2) {
            addCriterion("starttime not between", value1, value2, "starttime");
            return (Criteria) this;
        }

        public Criteria andEndtimeIsNull() {
            addCriterion("endtime is null");
            return (Criteria) this;
        }

        public Criteria andEndtimeIsNotNull() {
            addCriterion("endtime is not null");
            return (Criteria) this;
        }

        public Criteria andEndtimeEqualTo(Date value) {
            addCriterion("endtime =", value, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeNotEqualTo(Date value) {
            addCriterion("endtime <>", value, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeGreaterThan(Date value) {
            addCriterion("endtime >", value, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("endtime >=", value, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeLessThan(Date value) {
            addCriterion("endtime <", value, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeLessThanOrEqualTo(Date value) {
            addCriterion("endtime <=", value, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeIn(List<Date> values) {
            addCriterion("endtime in", values, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeNotIn(List<Date> values) {
            addCriterion("endtime not in", values, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeBetween(Date value1, Date value2) {
            addCriterion("endtime between", value1, value2, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeNotBetween(Date value1, Date value2) {
            addCriterion("endtime not between", value1, value2, "endtime");
            return (Criteria) this;
        }

        public Criteria andTimecostIsNull() {
            addCriterion("timecost is null");
            return (Criteria) this;
        }

        public Criteria andTimecostIsNotNull() {
            addCriterion("timecost is not null");
            return (Criteria) this;
        }

        public Criteria andTimecostEqualTo(Integer value) {
            addCriterion("timecost =", value, "timecost");
            return (Criteria) this;
        }

        public Criteria andTimecostNotEqualTo(Integer value) {
            addCriterion("timecost <>", value, "timecost");
            return (Criteria) this;
        }

        public Criteria andTimecostGreaterThan(Integer value) {
            addCriterion("timecost >", value, "timecost");
            return (Criteria) this;
        }

        public Criteria andTimecostGreaterThanOrEqualTo(Integer value) {
            addCriterion("timecost >=", value, "timecost");
            return (Criteria) this;
        }

        public Criteria andTimecostLessThan(Integer value) {
            addCriterion("timecost <", value, "timecost");
            return (Criteria) this;
        }

        public Criteria andTimecostLessThanOrEqualTo(Integer value) {
            addCriterion("timecost <=", value, "timecost");
            return (Criteria) this;
        }

        public Criteria andTimecostIn(List<Integer> values) {
            addCriterion("timecost in", values, "timecost");
            return (Criteria) this;
        }

        public Criteria andTimecostNotIn(List<Integer> values) {
            addCriterion("timecost not in", values, "timecost");
            return (Criteria) this;
        }

        public Criteria andTimecostBetween(Integer value1, Integer value2) {
            addCriterion("timecost between", value1, value2, "timecost");
            return (Criteria) this;
        }

        public Criteria andTimecostNotBetween(Integer value1, Integer value2) {
            addCriterion("timecost not between", value1, value2, "timecost");
            return (Criteria) this;
        }

        public Criteria andPatrolattendanceIsNull() {
            addCriterion("patrolattendance is null");
            return (Criteria) this;
        }

        public Criteria andPatrolattendanceIsNotNull() {
            addCriterion("patrolattendance is not null");
            return (Criteria) this;
        }

        public Criteria andPatrolattendanceEqualTo(String value) {
            addCriterion("patrolattendance =", value, "patrolattendance");
            return (Criteria) this;
        }

        public Criteria andPatrolattendanceNotEqualTo(String value) {
            addCriterion("patrolattendance <>", value, "patrolattendance");
            return (Criteria) this;
        }

        public Criteria andPatrolattendanceGreaterThan(String value) {
            addCriterion("patrolattendance >", value, "patrolattendance");
            return (Criteria) this;
        }

        public Criteria andPatrolattendanceGreaterThanOrEqualTo(String value) {
            addCriterion("patrolattendance >=", value, "patrolattendance");
            return (Criteria) this;
        }

        public Criteria andPatrolattendanceLessThan(String value) {
            addCriterion("patrolattendance <", value, "patrolattendance");
            return (Criteria) this;
        }

        public Criteria andPatrolattendanceLessThanOrEqualTo(String value) {
            addCriterion("patrolattendance <=", value, "patrolattendance");
            return (Criteria) this;
        }

        public Criteria andPatrolattendanceLike(String value) {
            addCriterion("patrolattendance like", value, "patrolattendance");
            return (Criteria) this;
        }

        public Criteria andPatrolattendanceNotLike(String value) {
            addCriterion("patrolattendance not like", value, "patrolattendance");
            return (Criteria) this;
        }

        public Criteria andPatrolattendanceIn(List<String> values) {
            addCriterion("patrolattendance in", values, "patrolattendance");
            return (Criteria) this;
        }

        public Criteria andPatrolattendanceNotIn(List<String> values) {
            addCriterion("patrolattendance not in", values, "patrolattendance");
            return (Criteria) this;
        }

        public Criteria andPatrolattendanceBetween(String value1, String value2) {
            addCriterion("patrolattendance between", value1, value2, "patrolattendance");
            return (Criteria) this;
        }

        public Criteria andPatrolattendanceNotBetween(String value1, String value2) {
            addCriterion("patrolattendance not between", value1, value2, "patrolattendance");
            return (Criteria) this;
        }

        public Criteria andPatrolresultIsNull() {
            addCriterion("patrolresult is null");
            return (Criteria) this;
        }

        public Criteria andPatrolresultIsNotNull() {
            addCriterion("patrolresult is not null");
            return (Criteria) this;
        }

        public Criteria andPatrolresultEqualTo(String value) {
            addCriterion("patrolresult =", value, "patrolresult");
            return (Criteria) this;
        }

        public Criteria andPatrolresultNotEqualTo(String value) {
            addCriterion("patrolresult <>", value, "patrolresult");
            return (Criteria) this;
        }

        public Criteria andPatrolresultGreaterThan(String value) {
            addCriterion("patrolresult >", value, "patrolresult");
            return (Criteria) this;
        }

        public Criteria andPatrolresultGreaterThanOrEqualTo(String value) {
            addCriterion("patrolresult >=", value, "patrolresult");
            return (Criteria) this;
        }

        public Criteria andPatrolresultLessThan(String value) {
            addCriterion("patrolresult <", value, "patrolresult");
            return (Criteria) this;
        }

        public Criteria andPatrolresultLessThanOrEqualTo(String value) {
            addCriterion("patrolresult <=", value, "patrolresult");
            return (Criteria) this;
        }

        public Criteria andPatrolresultLike(String value) {
            addCriterion("patrolresult like", value, "patrolresult");
            return (Criteria) this;
        }

        public Criteria andPatrolresultNotLike(String value) {
            addCriterion("patrolresult not like", value, "patrolresult");
            return (Criteria) this;
        }

        public Criteria andPatrolresultIn(List<String> values) {
            addCriterion("patrolresult in", values, "patrolresult");
            return (Criteria) this;
        }

        public Criteria andPatrolresultNotIn(List<String> values) {
            addCriterion("patrolresult not in", values, "patrolresult");
            return (Criteria) this;
        }

        public Criteria andPatrolresultBetween(String value1, String value2) {
            addCriterion("patrolresult between", value1, value2, "patrolresult");
            return (Criteria) this;
        }

        public Criteria andPatrolresultNotBetween(String value1, String value2) {
            addCriterion("patrolresult not between", value1, value2, "patrolresult");
            return (Criteria) this;
        }

        public Criteria andPatroldateIsNull() {
            addCriterion("patroldate is null");
            return (Criteria) this;
        }

        public Criteria andPatroldateIsNotNull() {
            addCriterion("patroldate is not null");
            return (Criteria) this;
        }

        public Criteria andPatroldateEqualTo(Date value) {
            addCriterionForJDBCDate("patroldate =", value, "patroldate");
            return (Criteria) this;
        }

        public Criteria andPatroldateNotEqualTo(Date value) {
            addCriterionForJDBCDate("patroldate <>", value, "patroldate");
            return (Criteria) this;
        }

        public Criteria andPatroldateGreaterThan(Date value) {
            addCriterionForJDBCDate("patroldate >", value, "patroldate");
            return (Criteria) this;
        }

        public Criteria andPatroldateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("patroldate >=", value, "patroldate");
            return (Criteria) this;
        }

        public Criteria andPatroldateLessThan(Date value) {
            addCriterionForJDBCDate("patroldate <", value, "patroldate");
            return (Criteria) this;
        }

        public Criteria andPatroldateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("patroldate <=", value, "patroldate");
            return (Criteria) this;
        }

        public Criteria andPatroldateIn(List<Date> values) {
            addCriterionForJDBCDate("patroldate in", values, "patroldate");
            return (Criteria) this;
        }

        public Criteria andPatroldateNotIn(List<Date> values) {
            addCriterionForJDBCDate("patroldate not in", values, "patroldate");
            return (Criteria) this;
        }

        public Criteria andPatroldateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("patroldate between", value1, value2, "patroldate");
            return (Criteria) this;
        }

        public Criteria andPatroldateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("patroldate not between", value1, value2, "patroldate");
            return (Criteria) this;
        }

        public Criteria andReserved1IsNull() {
            addCriterion("reserved1 is null");
            return (Criteria) this;
        }

        public Criteria andReserved1IsNotNull() {
            addCriterion("reserved1 is not null");
            return (Criteria) this;
        }

        public Criteria andReserved1EqualTo(String value) {
            addCriterion("reserved1 =", value, "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved1NotEqualTo(String value) {
            addCriterion("reserved1 <>", value, "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved1GreaterThan(String value) {
            addCriterion("reserved1 >", value, "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved1GreaterThanOrEqualTo(String value) {
            addCriterion("reserved1 >=", value, "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved1LessThan(String value) {
            addCriterion("reserved1 <", value, "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved1LessThanOrEqualTo(String value) {
            addCriterion("reserved1 <=", value, "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved1Like(String value) {
            addCriterion("reserved1 like", value, "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved1NotLike(String value) {
            addCriterion("reserved1 not like", value, "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved1In(List<String> values) {
            addCriterion("reserved1 in", values, "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved1NotIn(List<String> values) {
            addCriterion("reserved1 not in", values, "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved1Between(String value1, String value2) {
            addCriterion("reserved1 between", value1, value2, "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved1NotBetween(String value1, String value2) {
            addCriterion("reserved1 not between", value1, value2, "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved2IsNull() {
            addCriterion("reserved2 is null");
            return (Criteria) this;
        }

        public Criteria andReserved2IsNotNull() {
            addCriterion("reserved2 is not null");
            return (Criteria) this;
        }

        public Criteria andReserved2EqualTo(String value) {
            addCriterion("reserved2 =", value, "reserved2");
            return (Criteria) this;
        }

        public Criteria andReserved2NotEqualTo(String value) {
            addCriterion("reserved2 <>", value, "reserved2");
            return (Criteria) this;
        }

        public Criteria andReserved2GreaterThan(String value) {
            addCriterion("reserved2 >", value, "reserved2");
            return (Criteria) this;
        }

        public Criteria andReserved2GreaterThanOrEqualTo(String value) {
            addCriterion("reserved2 >=", value, "reserved2");
            return (Criteria) this;
        }

        public Criteria andReserved2LessThan(String value) {
            addCriterion("reserved2 <", value, "reserved2");
            return (Criteria) this;
        }

        public Criteria andReserved2LessThanOrEqualTo(String value) {
            addCriterion("reserved2 <=", value, "reserved2");
            return (Criteria) this;
        }

        public Criteria andReserved2Like(String value) {
            addCriterion("reserved2 like", value, "reserved2");
            return (Criteria) this;
        }

        public Criteria andReserved2NotLike(String value) {
            addCriterion("reserved2 not like", value, "reserved2");
            return (Criteria) this;
        }

        public Criteria andReserved2In(List<String> values) {
            addCriterion("reserved2 in", values, "reserved2");
            return (Criteria) this;
        }

        public Criteria andReserved2NotIn(List<String> values) {
            addCriterion("reserved2 not in", values, "reserved2");
            return (Criteria) this;
        }

        public Criteria andReserved2Between(String value1, String value2) {
            addCriterion("reserved2 between", value1, value2, "reserved2");
            return (Criteria) this;
        }

        public Criteria andReserved2NotBetween(String value1, String value2) {
            addCriterion("reserved2 not between", value1, value2, "reserved2");
            return (Criteria) this;
        }

        public Criteria andReserved3IsNull() {
            addCriterion("reserved3 is null");
            return (Criteria) this;
        }

        public Criteria andReserved3IsNotNull() {
            addCriterion("reserved3 is not null");
            return (Criteria) this;
        }

        public Criteria andReserved3EqualTo(String value) {
            addCriterion("reserved3 =", value, "reserved3");
            return (Criteria) this;
        }

        public Criteria andReserved3NotEqualTo(String value) {
            addCriterion("reserved3 <>", value, "reserved3");
            return (Criteria) this;
        }

        public Criteria andReserved3GreaterThan(String value) {
            addCriterion("reserved3 >", value, "reserved3");
            return (Criteria) this;
        }

        public Criteria andReserved3GreaterThanOrEqualTo(String value) {
            addCriterion("reserved3 >=", value, "reserved3");
            return (Criteria) this;
        }

        public Criteria andReserved3LessThan(String value) {
            addCriterion("reserved3 <", value, "reserved3");
            return (Criteria) this;
        }

        public Criteria andReserved3LessThanOrEqualTo(String value) {
            addCriterion("reserved3 <=", value, "reserved3");
            return (Criteria) this;
        }

        public Criteria andReserved3Like(String value) {
            addCriterion("reserved3 like", value, "reserved3");
            return (Criteria) this;
        }

        public Criteria andReserved3NotLike(String value) {
            addCriterion("reserved3 not like", value, "reserved3");
            return (Criteria) this;
        }

        public Criteria andReserved3In(List<String> values) {
            addCriterion("reserved3 in", values, "reserved3");
            return (Criteria) this;
        }

        public Criteria andReserved3NotIn(List<String> values) {
            addCriterion("reserved3 not in", values, "reserved3");
            return (Criteria) this;
        }

        public Criteria andReserved3Between(String value1, String value2) {
            addCriterion("reserved3 between", value1, value2, "reserved3");
            return (Criteria) this;
        }

        public Criteria andReserved3NotBetween(String value1, String value2) {
            addCriterion("reserved3 not between", value1, value2, "reserved3");
            return (Criteria) this;
        }

        public Criteria andReserved4IsNull() {
            addCriterion("reserved4 is null");
            return (Criteria) this;
        }

        public Criteria andReserved4IsNotNull() {
            addCriterion("reserved4 is not null");
            return (Criteria) this;
        }

        public Criteria andReserved4EqualTo(String value) {
            addCriterion("reserved4 =", value, "reserved4");
            return (Criteria) this;
        }

        public Criteria andReserved4NotEqualTo(String value) {
            addCriterion("reserved4 <>", value, "reserved4");
            return (Criteria) this;
        }

        public Criteria andReserved4GreaterThan(String value) {
            addCriterion("reserved4 >", value, "reserved4");
            return (Criteria) this;
        }

        public Criteria andReserved4GreaterThanOrEqualTo(String value) {
            addCriterion("reserved4 >=", value, "reserved4");
            return (Criteria) this;
        }

        public Criteria andReserved4LessThan(String value) {
            addCriterion("reserved4 <", value, "reserved4");
            return (Criteria) this;
        }

        public Criteria andReserved4LessThanOrEqualTo(String value) {
            addCriterion("reserved4 <=", value, "reserved4");
            return (Criteria) this;
        }

        public Criteria andReserved4Like(String value) {
            addCriterion("reserved4 like", value, "reserved4");
            return (Criteria) this;
        }

        public Criteria andReserved4NotLike(String value) {
            addCriterion("reserved4 not like", value, "reserved4");
            return (Criteria) this;
        }

        public Criteria andReserved4In(List<String> values) {
            addCriterion("reserved4 in", values, "reserved4");
            return (Criteria) this;
        }

        public Criteria andReserved4NotIn(List<String> values) {
            addCriterion("reserved4 not in", values, "reserved4");
            return (Criteria) this;
        }

        public Criteria andReserved4Between(String value1, String value2) {
            addCriterion("reserved4 between", value1, value2, "reserved4");
            return (Criteria) this;
        }

        public Criteria andReserved4NotBetween(String value1, String value2) {
            addCriterion("reserved4 not between", value1, value2, "reserved4");
            return (Criteria) this;
        }

        public Criteria andReserved5IsNull() {
            addCriterion("reserved5 is null");
            return (Criteria) this;
        }

        public Criteria andReserved5IsNotNull() {
            addCriterion("reserved5 is not null");
            return (Criteria) this;
        }

        public Criteria andReserved5EqualTo(String value) {
            addCriterion("reserved5 =", value, "reserved5");
            return (Criteria) this;
        }

        public Criteria andReserved5NotEqualTo(String value) {
            addCriterion("reserved5 <>", value, "reserved5");
            return (Criteria) this;
        }

        public Criteria andReserved5GreaterThan(String value) {
            addCriterion("reserved5 >", value, "reserved5");
            return (Criteria) this;
        }

        public Criteria andReserved5GreaterThanOrEqualTo(String value) {
            addCriterion("reserved5 >=", value, "reserved5");
            return (Criteria) this;
        }

        public Criteria andReserved5LessThan(String value) {
            addCriterion("reserved5 <", value, "reserved5");
            return (Criteria) this;
        }

        public Criteria andReserved5LessThanOrEqualTo(String value) {
            addCriterion("reserved5 <=", value, "reserved5");
            return (Criteria) this;
        }

        public Criteria andReserved5Like(String value) {
            addCriterion("reserved5 like", value, "reserved5");
            return (Criteria) this;
        }

        public Criteria andReserved5NotLike(String value) {
            addCriterion("reserved5 not like", value, "reserved5");
            return (Criteria) this;
        }

        public Criteria andReserved5In(List<String> values) {
            addCriterion("reserved5 in", values, "reserved5");
            return (Criteria) this;
        }

        public Criteria andReserved5NotIn(List<String> values) {
            addCriterion("reserved5 not in", values, "reserved5");
            return (Criteria) this;
        }

        public Criteria andReserved5Between(String value1, String value2) {
            addCriterion("reserved5 between", value1, value2, "reserved5");
            return (Criteria) this;
        }

        public Criteria andReserved5NotBetween(String value1, String value2) {
            addCriterion("reserved5 not between", value1, value2, "reserved5");
            return (Criteria) this;
        }

        public Criteria andReserved6IsNull() {
            addCriterion("reserved6 is null");
            return (Criteria) this;
        }

        public Criteria andReserved6IsNotNull() {
            addCriterion("reserved6 is not null");
            return (Criteria) this;
        }

        public Criteria andReserved6EqualTo(String value) {
            addCriterion("reserved6 =", value, "reserved6");
            return (Criteria) this;
        }

        public Criteria andReserved6NotEqualTo(String value) {
            addCriterion("reserved6 <>", value, "reserved6");
            return (Criteria) this;
        }

        public Criteria andReserved6GreaterThan(String value) {
            addCriterion("reserved6 >", value, "reserved6");
            return (Criteria) this;
        }

        public Criteria andReserved6GreaterThanOrEqualTo(String value) {
            addCriterion("reserved6 >=", value, "reserved6");
            return (Criteria) this;
        }

        public Criteria andReserved6LessThan(String value) {
            addCriterion("reserved6 <", value, "reserved6");
            return (Criteria) this;
        }

        public Criteria andReserved6LessThanOrEqualTo(String value) {
            addCriterion("reserved6 <=", value, "reserved6");
            return (Criteria) this;
        }

        public Criteria andReserved6Like(String value) {
            addCriterion("reserved6 like", value, "reserved6");
            return (Criteria) this;
        }

        public Criteria andReserved6NotLike(String value) {
            addCriterion("reserved6 not like", value, "reserved6");
            return (Criteria) this;
        }

        public Criteria andReserved6In(List<String> values) {
            addCriterion("reserved6 in", values, "reserved6");
            return (Criteria) this;
        }

        public Criteria andReserved6NotIn(List<String> values) {
            addCriterion("reserved6 not in", values, "reserved6");
            return (Criteria) this;
        }

        public Criteria andReserved6Between(String value1, String value2) {
            addCriterion("reserved6 between", value1, value2, "reserved6");
            return (Criteria) this;
        }

        public Criteria andReserved6NotBetween(String value1, String value2) {
            addCriterion("reserved6 not between", value1, value2, "reserved6");
            return (Criteria) this;
        }


        public Criteria andAppStarttimeGreaterThanOrEqualTo(String value) {
            addCriterion("starttime >=", value, "starttime");
            return (Criteria) this;
        }

        public Criteria andAppEndtimeGreaterThanOrEqualTo(String value) {
            addCriterion("starttime <=", value, "starttime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hb_patroltask
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hb_patroltask
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}