package com.example.demo.global.domain.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class HbPrivilegeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hb_privilege
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hb_privilege
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hb_privilege
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_privilege
     *
     * @mbg.generated
     */
    public HbPrivilegeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_privilege
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_privilege
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_privilege
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_privilege
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_privilege
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_privilege
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_privilege
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_privilege
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_privilege
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_privilege
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hb_privilege
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPrivilegeidIsNull() {
            addCriterion("privilegeid is null");
            return (Criteria) this;
        }

        public Criteria andPrivilegeidIsNotNull() {
            addCriterion("privilegeid is not null");
            return (Criteria) this;
        }

        public Criteria andPrivilegeidEqualTo(String value) {
            addCriterion("privilegeid =", value, "privilegeid");
            return (Criteria) this;
        }

        public Criteria andPrivilegeidNotEqualTo(String value) {
            addCriterion("privilegeid <>", value, "privilegeid");
            return (Criteria) this;
        }

        public Criteria andPrivilegeidGreaterThan(String value) {
            addCriterion("privilegeid >", value, "privilegeid");
            return (Criteria) this;
        }

        public Criteria andPrivilegeidGreaterThanOrEqualTo(String value) {
            addCriterion("privilegeid >=", value, "privilegeid");
            return (Criteria) this;
        }

        public Criteria andPrivilegeidLessThan(String value) {
            addCriterion("privilegeid <", value, "privilegeid");
            return (Criteria) this;
        }

        public Criteria andPrivilegeidLessThanOrEqualTo(String value) {
            addCriterion("privilegeid <=", value, "privilegeid");
            return (Criteria) this;
        }

        public Criteria andPrivilegeidLike(String value) {
            addCriterion("privilegeid like", value, "privilegeid");
            return (Criteria) this;
        }

        public Criteria andPrivilegeidNotLike(String value) {
            addCriterion("privilegeid not like", value, "privilegeid");
            return (Criteria) this;
        }

        public Criteria andPrivilegeidIn(List<String> values) {
            addCriterion("privilegeid in", values, "privilegeid");
            return (Criteria) this;
        }

        public Criteria andPrivilegeidNotIn(List<String> values) {
            addCriterion("privilegeid not in", values, "privilegeid");
            return (Criteria) this;
        }

        public Criteria andPrivilegeidBetween(String value1, String value2) {
            addCriterion("privilegeid between", value1, value2, "privilegeid");
            return (Criteria) this;
        }

        public Criteria andPrivilegeidNotBetween(String value1, String value2) {
            addCriterion("privilegeid not between", value1, value2, "privilegeid");
            return (Criteria) this;
        }

        public Criteria andMenuidIsNull() {
            addCriterion("menuid is null");
            return (Criteria) this;
        }

        public Criteria andMenuidIsNotNull() {
            addCriterion("menuid is not null");
            return (Criteria) this;
        }

        public Criteria andMenuidEqualTo(String value) {
            addCriterion("menuid =", value, "menuid");
            return (Criteria) this;
        }

        public Criteria andMenuidNotEqualTo(String value) {
            addCriterion("menuid <>", value, "menuid");
            return (Criteria) this;
        }

        public Criteria andMenuidGreaterThan(String value) {
            addCriterion("menuid >", value, "menuid");
            return (Criteria) this;
        }

        public Criteria andMenuidGreaterThanOrEqualTo(String value) {
            addCriterion("menuid >=", value, "menuid");
            return (Criteria) this;
        }

        public Criteria andMenuidLessThan(String value) {
            addCriterion("menuid <", value, "menuid");
            return (Criteria) this;
        }

        public Criteria andMenuidLessThanOrEqualTo(String value) {
            addCriterion("menuid <=", value, "menuid");
            return (Criteria) this;
        }

        public Criteria andMenuidLike(String value) {
            addCriterion("menuid like", value, "menuid");
            return (Criteria) this;
        }

        public Criteria andMenuidNotLike(String value) {
            addCriterion("menuid not like", value, "menuid");
            return (Criteria) this;
        }

        public Criteria andMenuidIn(List<String> values) {
            addCriterion("menuid in", values, "menuid");
            return (Criteria) this;
        }

        public Criteria andMenuidNotIn(List<String> values) {
            addCriterion("menuid not in", values, "menuid");
            return (Criteria) this;
        }

        public Criteria andMenuidBetween(String value1, String value2) {
            addCriterion("menuid between", value1, value2, "menuid");
            return (Criteria) this;
        }

        public Criteria andMenuidNotBetween(String value1, String value2) {
            addCriterion("menuid not between", value1, value2, "menuid");
            return (Criteria) this;
        }

        public Criteria andBtnidIsNull() {
            addCriterion("btnid is null");
            return (Criteria) this;
        }

        public Criteria andBtnidIsNotNull() {
            addCriterion("btnid is not null");
            return (Criteria) this;
        }

        public Criteria andBtnidEqualTo(String value) {
            addCriterion("btnid =", value, "btnid");
            return (Criteria) this;
        }

        public Criteria andBtnidNotEqualTo(String value) {
            addCriterion("btnid <>", value, "btnid");
            return (Criteria) this;
        }

        public Criteria andBtnidGreaterThan(String value) {
            addCriterion("btnid >", value, "btnid");
            return (Criteria) this;
        }

        public Criteria andBtnidGreaterThanOrEqualTo(String value) {
            addCriterion("btnid >=", value, "btnid");
            return (Criteria) this;
        }

        public Criteria andBtnidLessThan(String value) {
            addCriterion("btnid <", value, "btnid");
            return (Criteria) this;
        }

        public Criteria andBtnidLessThanOrEqualTo(String value) {
            addCriterion("btnid <=", value, "btnid");
            return (Criteria) this;
        }

        public Criteria andBtnidLike(String value) {
            addCriterion("btnid like", value, "btnid");
            return (Criteria) this;
        }

        public Criteria andBtnidNotLike(String value) {
            addCriterion("btnid not like", value, "btnid");
            return (Criteria) this;
        }

        public Criteria andBtnidIn(List<String> values) {
            addCriterion("btnid in", values, "btnid");
            return (Criteria) this;
        }

        public Criteria andBtnidNotIn(List<String> values) {
            addCriterion("btnid not in", values, "btnid");
            return (Criteria) this;
        }

        public Criteria andBtnidBetween(String value1, String value2) {
            addCriterion("btnid between", value1, value2, "btnid");
            return (Criteria) this;
        }

        public Criteria andBtnidNotBetween(String value1, String value2) {
            addCriterion("btnid not between", value1, value2, "btnid");
            return (Criteria) this;
        }

        public Criteria andBtnnameIsNull() {
            addCriterion("btnname is null");
            return (Criteria) this;
        }

        public Criteria andBtnnameIsNotNull() {
            addCriterion("btnname is not null");
            return (Criteria) this;
        }

        public Criteria andBtnnameEqualTo(String value) {
            addCriterion("btnname =", value, "btnname");
            return (Criteria) this;
        }

        public Criteria andBtnnameNotEqualTo(String value) {
            addCriterion("btnname <>", value, "btnname");
            return (Criteria) this;
        }

        public Criteria andBtnnameGreaterThan(String value) {
            addCriterion("btnname >", value, "btnname");
            return (Criteria) this;
        }

        public Criteria andBtnnameGreaterThanOrEqualTo(String value) {
            addCriterion("btnname >=", value, "btnname");
            return (Criteria) this;
        }

        public Criteria andBtnnameLessThan(String value) {
            addCriterion("btnname <", value, "btnname");
            return (Criteria) this;
        }

        public Criteria andBtnnameLessThanOrEqualTo(String value) {
            addCriterion("btnname <=", value, "btnname");
            return (Criteria) this;
        }

        public Criteria andBtnnameLike(String value) {
            addCriterion("btnname like", value, "btnname");
            return (Criteria) this;
        }

        public Criteria andBtnnameNotLike(String value) {
            addCriterion("btnname not like", value, "btnname");
            return (Criteria) this;
        }

        public Criteria andBtnnameIn(List<String> values) {
            addCriterion("btnname in", values, "btnname");
            return (Criteria) this;
        }

        public Criteria andBtnnameNotIn(List<String> values) {
            addCriterion("btnname not in", values, "btnname");
            return (Criteria) this;
        }

        public Criteria andBtnnameBetween(String value1, String value2) {
            addCriterion("btnname between", value1, value2, "btnname");
            return (Criteria) this;
        }

        public Criteria andBtnnameNotBetween(String value1, String value2) {
            addCriterion("btnname not between", value1, value2, "btnname");
            return (Criteria) this;
        }

        public Criteria andCreatdtimeIsNull() {
            addCriterion("creatdtime is null");
            return (Criteria) this;
        }

        public Criteria andCreatdtimeIsNotNull() {
            addCriterion("creatdtime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatdtimeEqualTo(Date value) {
            addCriterion("creatdtime =", value, "creatdtime");
            return (Criteria) this;
        }

        public Criteria andCreatdtimeNotEqualTo(Date value) {
            addCriterion("creatdtime <>", value, "creatdtime");
            return (Criteria) this;
        }

        public Criteria andCreatdtimeGreaterThan(Date value) {
            addCriterion("creatdtime >", value, "creatdtime");
            return (Criteria) this;
        }

        public Criteria andCreatdtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("creatdtime >=", value, "creatdtime");
            return (Criteria) this;
        }

        public Criteria andCreatdtimeLessThan(Date value) {
            addCriterion("creatdtime <", value, "creatdtime");
            return (Criteria) this;
        }

        public Criteria andCreatdtimeLessThanOrEqualTo(Date value) {
            addCriterion("creatdtime <=", value, "creatdtime");
            return (Criteria) this;
        }

        public Criteria andCreatdtimeIn(List<Date> values) {
            addCriterion("creatdtime in", values, "creatdtime");
            return (Criteria) this;
        }

        public Criteria andCreatdtimeNotIn(List<Date> values) {
            addCriterion("creatdtime not in", values, "creatdtime");
            return (Criteria) this;
        }

        public Criteria andCreatdtimeBetween(Date value1, Date value2) {
            addCriterion("creatdtime between", value1, value2, "creatdtime");
            return (Criteria) this;
        }

        public Criteria andCreatdtimeNotBetween(Date value1, Date value2) {
            addCriterion("creatdtime not between", value1, value2, "creatdtime");
            return (Criteria) this;
        }

        public Criteria andReserved1IsNull() {
            addCriterion("reserved1 is null");
            return (Criteria) this;
        }

        public Criteria andReserved1IsNotNull() {
            addCriterion("reserved1 is not null");
            return (Criteria) this;
        }

        public Criteria andReserved1EqualTo(String value) {
            addCriterion("reserved1 =", value, "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved1NotEqualTo(String value) {
            addCriterion("reserved1 <>", value, "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved1GreaterThan(String value) {
            addCriterion("reserved1 >", value, "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved1GreaterThanOrEqualTo(String value) {
            addCriterion("reserved1 >=", value, "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved1LessThan(String value) {
            addCriterion("reserved1 <", value, "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved1LessThanOrEqualTo(String value) {
            addCriterion("reserved1 <=", value, "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved1Like(String value) {
            addCriterion("reserved1 like", value, "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved1NotLike(String value) {
            addCriterion("reserved1 not like", value, "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved1In(List<String> values) {
            addCriterion("reserved1 in", values, "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved1NotIn(List<String> values) {
            addCriterion("reserved1 not in", values, "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved1Between(String value1, String value2) {
            addCriterion("reserved1 between", value1, value2, "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved1NotBetween(String value1, String value2) {
            addCriterion("reserved1 not between", value1, value2, "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved2IsNull() {
            addCriterion("reserved2 is null");
            return (Criteria) this;
        }

        public Criteria andReserved2IsNotNull() {
            addCriterion("reserved2 is not null");
            return (Criteria) this;
        }

        public Criteria andReserved2EqualTo(String value) {
            addCriterion("reserved2 =", value, "reserved2");
            return (Criteria) this;
        }

        public Criteria andReserved2NotEqualTo(String value) {
            addCriterion("reserved2 <>", value, "reserved2");
            return (Criteria) this;
        }

        public Criteria andReserved2GreaterThan(String value) {
            addCriterion("reserved2 >", value, "reserved2");
            return (Criteria) this;
        }

        public Criteria andReserved2GreaterThanOrEqualTo(String value) {
            addCriterion("reserved2 >=", value, "reserved2");
            return (Criteria) this;
        }

        public Criteria andReserved2LessThan(String value) {
            addCriterion("reserved2 <", value, "reserved2");
            return (Criteria) this;
        }

        public Criteria andReserved2LessThanOrEqualTo(String value) {
            addCriterion("reserved2 <=", value, "reserved2");
            return (Criteria) this;
        }

        public Criteria andReserved2Like(String value) {
            addCriterion("reserved2 like", value, "reserved2");
            return (Criteria) this;
        }

        public Criteria andReserved2NotLike(String value) {
            addCriterion("reserved2 not like", value, "reserved2");
            return (Criteria) this;
        }

        public Criteria andReserved2In(List<String> values) {
            addCriterion("reserved2 in", values, "reserved2");
            return (Criteria) this;
        }

        public Criteria andReserved2NotIn(List<String> values) {
            addCriterion("reserved2 not in", values, "reserved2");
            return (Criteria) this;
        }

        public Criteria andReserved2Between(String value1, String value2) {
            addCriterion("reserved2 between", value1, value2, "reserved2");
            return (Criteria) this;
        }

        public Criteria andReserved2NotBetween(String value1, String value2) {
            addCriterion("reserved2 not between", value1, value2, "reserved2");
            return (Criteria) this;
        }

        public Criteria andReserved3IsNull() {
            addCriterion("reserved3 is null");
            return (Criteria) this;
        }

        public Criteria andReserved3IsNotNull() {
            addCriterion("reserved3 is not null");
            return (Criteria) this;
        }

        public Criteria andReserved3EqualTo(String value) {
            addCriterion("reserved3 =", value, "reserved3");
            return (Criteria) this;
        }

        public Criteria andReserved3NotEqualTo(String value) {
            addCriterion("reserved3 <>", value, "reserved3");
            return (Criteria) this;
        }

        public Criteria andReserved3GreaterThan(String value) {
            addCriterion("reserved3 >", value, "reserved3");
            return (Criteria) this;
        }

        public Criteria andReserved3GreaterThanOrEqualTo(String value) {
            addCriterion("reserved3 >=", value, "reserved3");
            return (Criteria) this;
        }

        public Criteria andReserved3LessThan(String value) {
            addCriterion("reserved3 <", value, "reserved3");
            return (Criteria) this;
        }

        public Criteria andReserved3LessThanOrEqualTo(String value) {
            addCriterion("reserved3 <=", value, "reserved3");
            return (Criteria) this;
        }

        public Criteria andReserved3Like(String value) {
            addCriterion("reserved3 like", value, "reserved3");
            return (Criteria) this;
        }

        public Criteria andReserved3NotLike(String value) {
            addCriterion("reserved3 not like", value, "reserved3");
            return (Criteria) this;
        }

        public Criteria andReserved3In(List<String> values) {
            addCriterion("reserved3 in", values, "reserved3");
            return (Criteria) this;
        }

        public Criteria andReserved3NotIn(List<String> values) {
            addCriterion("reserved3 not in", values, "reserved3");
            return (Criteria) this;
        }

        public Criteria andReserved3Between(String value1, String value2) {
            addCriterion("reserved3 between", value1, value2, "reserved3");
            return (Criteria) this;
        }

        public Criteria andReserved3NotBetween(String value1, String value2) {
            addCriterion("reserved3 not between", value1, value2, "reserved3");
            return (Criteria) this;
        }

        public Criteria andReserved4IsNull() {
            addCriterion("reserved4 is null");
            return (Criteria) this;
        }

        public Criteria andReserved4IsNotNull() {
            addCriterion("reserved4 is not null");
            return (Criteria) this;
        }

        public Criteria andReserved4EqualTo(String value) {
            addCriterion("reserved4 =", value, "reserved4");
            return (Criteria) this;
        }

        public Criteria andReserved4NotEqualTo(String value) {
            addCriterion("reserved4 <>", value, "reserved4");
            return (Criteria) this;
        }

        public Criteria andReserved4GreaterThan(String value) {
            addCriterion("reserved4 >", value, "reserved4");
            return (Criteria) this;
        }

        public Criteria andReserved4GreaterThanOrEqualTo(String value) {
            addCriterion("reserved4 >=", value, "reserved4");
            return (Criteria) this;
        }

        public Criteria andReserved4LessThan(String value) {
            addCriterion("reserved4 <", value, "reserved4");
            return (Criteria) this;
        }

        public Criteria andReserved4LessThanOrEqualTo(String value) {
            addCriterion("reserved4 <=", value, "reserved4");
            return (Criteria) this;
        }

        public Criteria andReserved4Like(String value) {
            addCriterion("reserved4 like", value, "reserved4");
            return (Criteria) this;
        }

        public Criteria andReserved4NotLike(String value) {
            addCriterion("reserved4 not like", value, "reserved4");
            return (Criteria) this;
        }

        public Criteria andReserved4In(List<String> values) {
            addCriterion("reserved4 in", values, "reserved4");
            return (Criteria) this;
        }

        public Criteria andReserved4NotIn(List<String> values) {
            addCriterion("reserved4 not in", values, "reserved4");
            return (Criteria) this;
        }

        public Criteria andReserved4Between(String value1, String value2) {
            addCriterion("reserved4 between", value1, value2, "reserved4");
            return (Criteria) this;
        }

        public Criteria andReserved4NotBetween(String value1, String value2) {
            addCriterion("reserved4 not between", value1, value2, "reserved4");
            return (Criteria) this;
        }

        public Criteria andReserved5IsNull() {
            addCriterion("reserved5 is null");
            return (Criteria) this;
        }

        public Criteria andReserved5IsNotNull() {
            addCriterion("reserved5 is not null");
            return (Criteria) this;
        }

        public Criteria andReserved5EqualTo(String value) {
            addCriterion("reserved5 =", value, "reserved5");
            return (Criteria) this;
        }

        public Criteria andReserved5NotEqualTo(String value) {
            addCriterion("reserved5 <>", value, "reserved5");
            return (Criteria) this;
        }

        public Criteria andReserved5GreaterThan(String value) {
            addCriterion("reserved5 >", value, "reserved5");
            return (Criteria) this;
        }

        public Criteria andReserved5GreaterThanOrEqualTo(String value) {
            addCriterion("reserved5 >=", value, "reserved5");
            return (Criteria) this;
        }

        public Criteria andReserved5LessThan(String value) {
            addCriterion("reserved5 <", value, "reserved5");
            return (Criteria) this;
        }

        public Criteria andReserved5LessThanOrEqualTo(String value) {
            addCriterion("reserved5 <=", value, "reserved5");
            return (Criteria) this;
        }

        public Criteria andReserved5Like(String value) {
            addCriterion("reserved5 like", value, "reserved5");
            return (Criteria) this;
        }

        public Criteria andReserved5NotLike(String value) {
            addCriterion("reserved5 not like", value, "reserved5");
            return (Criteria) this;
        }

        public Criteria andReserved5In(List<String> values) {
            addCriterion("reserved5 in", values, "reserved5");
            return (Criteria) this;
        }

        public Criteria andReserved5NotIn(List<String> values) {
            addCriterion("reserved5 not in", values, "reserved5");
            return (Criteria) this;
        }

        public Criteria andReserved5Between(String value1, String value2) {
            addCriterion("reserved5 between", value1, value2, "reserved5");
            return (Criteria) this;
        }

        public Criteria andReserved5NotBetween(String value1, String value2) {
            addCriterion("reserved5 not between", value1, value2, "reserved5");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hb_privilege
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hb_privilege
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}