package com.example.demo.global.domain.model;

import java.util.Date;

public class HbPrivilege {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_privilege.privilegeid
     *
     * @mbg.generated
     */
    private String privilegeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_privilege.menuid
     *
     * @mbg.generated
     */
    private String menuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_privilege.btnid
     *
     * @mbg.generated
     */
    private String btnid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_privilege.btnname
     *
     * @mbg.generated
     */
    private String btnname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_privilege.creatdtime
     *
     * @mbg.generated
     */
    private Date creatdtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_privilege.reserved1
     *
     * @mbg.generated
     */
    private String reserved1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_privilege.reserved2
     *
     * @mbg.generated
     */
    private String reserved2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_privilege.reserved3
     *
     * @mbg.generated
     */
    private String reserved3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_privilege.reserved4
     *
     * @mbg.generated
     */
    private String reserved4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_privilege.reserved5
     *
     * @mbg.generated
     */
    private String reserved5;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_privilege.privilegeid
     *
     * @return the value of hb_privilege.privilegeid
     *
     * @mbg.generated
     */
    public String getPrivilegeid() {
        return privilegeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_privilege.privilegeid
     *
     * @param privilegeid the value for hb_privilege.privilegeid
     *
     * @mbg.generated
     */
    public void setPrivilegeid(String privilegeid) {
        this.privilegeid = privilegeid == null ? null : privilegeid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_privilege.menuid
     *
     * @return the value of hb_privilege.menuid
     *
     * @mbg.generated
     */
    public String getMenuid() {
        return menuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_privilege.menuid
     *
     * @param menuid the value for hb_privilege.menuid
     *
     * @mbg.generated
     */
    public void setMenuid(String menuid) {
        this.menuid = menuid == null ? null : menuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_privilege.btnid
     *
     * @return the value of hb_privilege.btnid
     *
     * @mbg.generated
     */
    public String getBtnid() {
        return btnid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_privilege.btnid
     *
     * @param btnid the value for hb_privilege.btnid
     *
     * @mbg.generated
     */
    public void setBtnid(String btnid) {
        this.btnid = btnid == null ? null : btnid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_privilege.btnname
     *
     * @return the value of hb_privilege.btnname
     *
     * @mbg.generated
     */
    public String getBtnname() {
        return btnname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_privilege.btnname
     *
     * @param btnname the value for hb_privilege.btnname
     *
     * @mbg.generated
     */
    public void setBtnname(String btnname) {
        this.btnname = btnname == null ? null : btnname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_privilege.creatdtime
     *
     * @return the value of hb_privilege.creatdtime
     *
     * @mbg.generated
     */
    public Date getCreatdtime() {
        return creatdtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_privilege.creatdtime
     *
     * @param creatdtime the value for hb_privilege.creatdtime
     *
     * @mbg.generated
     */
    public void setCreatdtime(Date creatdtime) {
        this.creatdtime = creatdtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_privilege.reserved1
     *
     * @return the value of hb_privilege.reserved1
     *
     * @mbg.generated
     */
    public String getReserved1() {
        return reserved1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_privilege.reserved1
     *
     * @param reserved1 the value for hb_privilege.reserved1
     *
     * @mbg.generated
     */
    public void setReserved1(String reserved1) {
        this.reserved1 = reserved1 == null ? null : reserved1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_privilege.reserved2
     *
     * @return the value of hb_privilege.reserved2
     *
     * @mbg.generated
     */
    public String getReserved2() {
        return reserved2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_privilege.reserved2
     *
     * @param reserved2 the value for hb_privilege.reserved2
     *
     * @mbg.generated
     */
    public void setReserved2(String reserved2) {
        this.reserved2 = reserved2 == null ? null : reserved2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_privilege.reserved3
     *
     * @return the value of hb_privilege.reserved3
     *
     * @mbg.generated
     */
    public String getReserved3() {
        return reserved3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_privilege.reserved3
     *
     * @param reserved3 the value for hb_privilege.reserved3
     *
     * @mbg.generated
     */
    public void setReserved3(String reserved3) {
        this.reserved3 = reserved3 == null ? null : reserved3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_privilege.reserved4
     *
     * @return the value of hb_privilege.reserved4
     *
     * @mbg.generated
     */
    public String getReserved4() {
        return reserved4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_privilege.reserved4
     *
     * @param reserved4 the value for hb_privilege.reserved4
     *
     * @mbg.generated
     */
    public void setReserved4(String reserved4) {
        this.reserved4 = reserved4 == null ? null : reserved4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_privilege.reserved5
     *
     * @return the value of hb_privilege.reserved5
     *
     * @mbg.generated
     */
    public String getReserved5() {
        return reserved5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_privilege.reserved5
     *
     * @param reserved5 the value for hb_privilege.reserved5
     *
     * @mbg.generated
     */
    public void setReserved5(String reserved5) {
        this.reserved5 = reserved5 == null ? null : reserved5.trim();
    }
}