package com.example.demo.global.domain.model;

import java.util.Date;

public class HbServices {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_services.uuid
     *
     * @mbg.generated
     */
    private String uuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_services.servicetype
     *
     * @mbg.generated
     */
    private String servicetype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_services.vehicleid
     *
     * @mbg.generated
     */
    private String vehicleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_services.drivername
     *
     * @mbg.generated
     */
    private String drivername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_services.licenseid
     *
     * @mbg.generated
     */
    private String licenseid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_services.orgid
     *
     * @mbg.generated
     */
    private String orgid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_services.orgname
     *
     * @mbg.generated
     */
    private String orgname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_services.servicestate
     *
     * @mbg.generated
     */
    private String servicestate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_services.createtime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_services.operid
     *
     * @mbg.generated
     */
    private String operid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_services.dealtime
     *
     * @mbg.generated
     */
    private Date dealtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_services.reserved1
     *
     * @mbg.generated
     */
    private String reserved1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_services.reserved2
     *
     * @mbg.generated
     */
    private String reserved2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_services.reserved3
     *
     * @mbg.generated
     */
    private String reserved3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_services.reserved4
     *
     * @mbg.generated
     */
    private String reserved4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_services.reserved5
     *
     * @mbg.generated
     */
    private String reserved5;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_services.uuid
     *
     * @return the value of hb_services.uuid
     *
     * @mbg.generated
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_services.uuid
     *
     * @param uuid the value for hb_services.uuid
     *
     * @mbg.generated
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_services.servicetype
     *
     * @return the value of hb_services.servicetype
     *
     * @mbg.generated
     */
    public String getServicetype() {
        return servicetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_services.servicetype
     *
     * @param servicetype the value for hb_services.servicetype
     *
     * @mbg.generated
     */
    public void setServicetype(String servicetype) {
        this.servicetype = servicetype == null ? null : servicetype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_services.vehicleid
     *
     * @return the value of hb_services.vehicleid
     *
     * @mbg.generated
     */
    public String getVehicleid() {
        return vehicleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_services.vehicleid
     *
     * @param vehicleid the value for hb_services.vehicleid
     *
     * @mbg.generated
     */
    public void setVehicleid(String vehicleid) {
        this.vehicleid = vehicleid == null ? null : vehicleid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_services.drivername
     *
     * @return the value of hb_services.drivername
     *
     * @mbg.generated
     */
    public String getDrivername() {
        return drivername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_services.drivername
     *
     * @param drivername the value for hb_services.drivername
     *
     * @mbg.generated
     */
    public void setDrivername(String drivername) {
        this.drivername = drivername == null ? null : drivername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_services.licenseid
     *
     * @return the value of hb_services.licenseid
     *
     * @mbg.generated
     */
    public String getLicenseid() {
        return licenseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_services.licenseid
     *
     * @param licenseid the value for hb_services.licenseid
     *
     * @mbg.generated
     */
    public void setLicenseid(String licenseid) {
        this.licenseid = licenseid == null ? null : licenseid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_services.orgid
     *
     * @return the value of hb_services.orgid
     *
     * @mbg.generated
     */
    public String getOrgid() {
        return orgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_services.orgid
     *
     * @param orgid the value for hb_services.orgid
     *
     * @mbg.generated
     */
    public void setOrgid(String orgid) {
        this.orgid = orgid == null ? null : orgid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_services.orgname
     *
     * @return the value of hb_services.orgname
     *
     * @mbg.generated
     */
    public String getOrgname() {
        return orgname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_services.orgname
     *
     * @param orgname the value for hb_services.orgname
     *
     * @mbg.generated
     */
    public void setOrgname(String orgname) {
        this.orgname = orgname == null ? null : orgname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_services.servicestate
     *
     * @return the value of hb_services.servicestate
     *
     * @mbg.generated
     */
    public String getServicestate() {
        return servicestate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_services.servicestate
     *
     * @param servicestate the value for hb_services.servicestate
     *
     * @mbg.generated
     */
    public void setServicestate(String servicestate) {
        this.servicestate = servicestate == null ? null : servicestate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_services.createtime
     *
     * @return the value of hb_services.createtime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_services.createtime
     *
     * @param createtime the value for hb_services.createtime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_services.operid
     *
     * @return the value of hb_services.operid
     *
     * @mbg.generated
     */
    public String getOperid() {
        return operid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_services.operid
     *
     * @param operid the value for hb_services.operid
     *
     * @mbg.generated
     */
    public void setOperid(String operid) {
        this.operid = operid == null ? null : operid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_services.dealtime
     *
     * @return the value of hb_services.dealtime
     *
     * @mbg.generated
     */
    public Date getDealtime() {
        return dealtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_services.dealtime
     *
     * @param dealtime the value for hb_services.dealtime
     *
     * @mbg.generated
     */
    public void setDealtime(Date dealtime) {
        this.dealtime = dealtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_services.reserved1
     *
     * @return the value of hb_services.reserved1
     *
     * @mbg.generated
     */
    public String getReserved1() {
        return reserved1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_services.reserved1
     *
     * @param reserved1 the value for hb_services.reserved1
     *
     * @mbg.generated
     */
    public void setReserved1(String reserved1) {
        this.reserved1 = reserved1 == null ? null : reserved1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_services.reserved2
     *
     * @return the value of hb_services.reserved2
     *
     * @mbg.generated
     */
    public String getReserved2() {
        return reserved2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_services.reserved2
     *
     * @param reserved2 the value for hb_services.reserved2
     *
     * @mbg.generated
     */
    public void setReserved2(String reserved2) {
        this.reserved2 = reserved2 == null ? null : reserved2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_services.reserved3
     *
     * @return the value of hb_services.reserved3
     *
     * @mbg.generated
     */
    public String getReserved3() {
        return reserved3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_services.reserved3
     *
     * @param reserved3 the value for hb_services.reserved3
     *
     * @mbg.generated
     */
    public void setReserved3(String reserved3) {
        this.reserved3 = reserved3 == null ? null : reserved3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_services.reserved4
     *
     * @return the value of hb_services.reserved4
     *
     * @mbg.generated
     */
    public String getReserved4() {
        return reserved4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_services.reserved4
     *
     * @param reserved4 the value for hb_services.reserved4
     *
     * @mbg.generated
     */
    public void setReserved4(String reserved4) {
        this.reserved4 = reserved4 == null ? null : reserved4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_services.reserved5
     *
     * @return the value of hb_services.reserved5
     *
     * @mbg.generated
     */
    public String getReserved5() {
        return reserved5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_services.reserved5
     *
     * @param reserved5 the value for hb_services.reserved5
     *
     * @mbg.generated
     */
    public void setReserved5(String reserved5) {
        this.reserved5 = reserved5 == null ? null : reserved5.trim();
    }
}