package com.example.demo.global.domain.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class HbVehicleExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hb_vehicle
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hb_vehicle
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hb_vehicle
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_vehicle
     *
     * @mbg.generated
     */
    public HbVehicleExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_vehicle
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_vehicle
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_vehicle
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_vehicle
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_vehicle
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_vehicle
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_vehicle
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_vehicle
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_vehicle
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_vehicle
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hb_vehicle
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andVehiclenoIsNull() {
            addCriterion("vehicleno is null");
            return (Criteria) this;
        }

        public Criteria andVehiclenoIsNotNull() {
            addCriterion("vehicleno is not null");
            return (Criteria) this;
        }

        public Criteria andVehiclenoEqualTo(String value) {
            addCriterion("vehicleno =", value, "vehicleno");
            return (Criteria) this;
        }

        public Criteria andVehiclenoNotEqualTo(String value) {
            addCriterion("vehicleno <>", value, "vehicleno");
            return (Criteria) this;
        }

        public Criteria andVehiclenoGreaterThan(String value) {
            addCriterion("vehicleno >", value, "vehicleno");
            return (Criteria) this;
        }

        public Criteria andVehiclenoGreaterThanOrEqualTo(String value) {
            addCriterion("vehicleno >=", value, "vehicleno");
            return (Criteria) this;
        }

        public Criteria andVehiclenoLessThan(String value) {
            addCriterion("vehicleno <", value, "vehicleno");
            return (Criteria) this;
        }

        public Criteria andVehiclenoLessThanOrEqualTo(String value) {
            addCriterion("vehicleno <=", value, "vehicleno");
            return (Criteria) this;
        }

        public Criteria andVehiclenoLike(String value) {
            addCriterion("vehicleno like", value, "vehicleno");
            return (Criteria) this;
        }

        public Criteria andVehiclenoNotLike(String value) {
            addCriterion("vehicleno not like", value, "vehicleno");
            return (Criteria) this;
        }

        public Criteria andVehiclenoIn(List<String> values) {
            addCriterion("vehicleno in", values, "vehicleno");
            return (Criteria) this;
        }

        public Criteria andVehiclenoNotIn(List<String> values) {
            addCriterion("vehicleno not in", values, "vehicleno");
            return (Criteria) this;
        }

        public Criteria andVehiclenoBetween(String value1, String value2) {
            addCriterion("vehicleno between", value1, value2, "vehicleno");
            return (Criteria) this;
        }

        public Criteria andVehiclenoNotBetween(String value1, String value2) {
            addCriterion("vehicleno not between", value1, value2, "vehicleno");
            return (Criteria) this;
        }

        public Criteria andVehicleidIsNull() {
            addCriterion("vehicleid is null");
            return (Criteria) this;
        }

        public Criteria andVehicleidIsNotNull() {
            addCriterion("vehicleid is not null");
            return (Criteria) this;
        }

        public Criteria andVehicleidEqualTo(String value) {
            addCriterion("vehicleid =", value, "vehicleid");
            return (Criteria) this;
        }

        public Criteria andVehicleidNotEqualTo(String value) {
            addCriterion("vehicleid <>", value, "vehicleid");
            return (Criteria) this;
        }

        public Criteria andVehicleidGreaterThan(String value) {
            addCriterion("vehicleid >", value, "vehicleid");
            return (Criteria) this;
        }

        public Criteria andVehicleidGreaterThanOrEqualTo(String value) {
            addCriterion("vehicleid >=", value, "vehicleid");
            return (Criteria) this;
        }

        public Criteria andVehicleidLessThan(String value) {
            addCriterion("vehicleid <", value, "vehicleid");
            return (Criteria) this;
        }

        public Criteria andVehicleidLessThanOrEqualTo(String value) {
            addCriterion("vehicleid <=", value, "vehicleid");
            return (Criteria) this;
        }

        public Criteria andVehicleidLike(String value) {
            addCriterion("vehicleid like", value, "vehicleid");
            return (Criteria) this;
        }

        public Criteria andVehicleidNotLike(String value) {
            addCriterion("vehicleid not like", value, "vehicleid");
            return (Criteria) this;
        }

        public Criteria andVehicleidIn(List<String> values) {
            addCriterion("vehicleid in", values, "vehicleid");
            return (Criteria) this;
        }

        public Criteria andVehicleidNotIn(List<String> values) {
            addCriterion("vehicleid not in", values, "vehicleid");
            return (Criteria) this;
        }

        public Criteria andVehicleidBetween(String value1, String value2) {
            addCriterion("vehicleid between", value1, value2, "vehicleid");
            return (Criteria) this;
        }

        public Criteria andVehicleidNotBetween(String value1, String value2) {
            addCriterion("vehicleid not between", value1, value2, "vehicleid");
            return (Criteria) this;
        }

        public Criteria andVehiclebrandIsNull() {
            addCriterion("vehiclebrand is null");
            return (Criteria) this;
        }

        public Criteria andVehiclebrandIsNotNull() {
            addCriterion("vehiclebrand is not null");
            return (Criteria) this;
        }

        public Criteria andVehiclebrandEqualTo(String value) {
            addCriterion("vehiclebrand =", value, "vehiclebrand");
            return (Criteria) this;
        }

        public Criteria andVehiclebrandNotEqualTo(String value) {
            addCriterion("vehiclebrand <>", value, "vehiclebrand");
            return (Criteria) this;
        }

        public Criteria andVehiclebrandGreaterThan(String value) {
            addCriterion("vehiclebrand >", value, "vehiclebrand");
            return (Criteria) this;
        }

        public Criteria andVehiclebrandGreaterThanOrEqualTo(String value) {
            addCriterion("vehiclebrand >=", value, "vehiclebrand");
            return (Criteria) this;
        }

        public Criteria andVehiclebrandLessThan(String value) {
            addCriterion("vehiclebrand <", value, "vehiclebrand");
            return (Criteria) this;
        }

        public Criteria andVehiclebrandLessThanOrEqualTo(String value) {
            addCriterion("vehiclebrand <=", value, "vehiclebrand");
            return (Criteria) this;
        }

        public Criteria andVehiclebrandLike(String value) {
            addCriterion("vehiclebrand like", value, "vehiclebrand");
            return (Criteria) this;
        }

        public Criteria andVehiclebrandNotLike(String value) {
            addCriterion("vehiclebrand not like", value, "vehiclebrand");
            return (Criteria) this;
        }

        public Criteria andVehiclebrandIn(List<String> values) {
            addCriterion("vehiclebrand in", values, "vehiclebrand");
            return (Criteria) this;
        }

        public Criteria andVehiclebrandNotIn(List<String> values) {
            addCriterion("vehiclebrand not in", values, "vehiclebrand");
            return (Criteria) this;
        }

        public Criteria andVehiclebrandBetween(String value1, String value2) {
            addCriterion("vehiclebrand between", value1, value2, "vehiclebrand");
            return (Criteria) this;
        }

        public Criteria andVehiclebrandNotBetween(String value1, String value2) {
            addCriterion("vehiclebrand not between", value1, value2, "vehiclebrand");
            return (Criteria) this;
        }

        public Criteria andVehicletypeIsNull() {
            addCriterion("vehicletype is null");
            return (Criteria) this;
        }

        public Criteria andVehicletypeIsNotNull() {
            addCriterion("vehicletype is not null");
            return (Criteria) this;
        }

        public Criteria andVehicletypeEqualTo(String value) {
            addCriterion("vehicletype =", value, "vehicletype");
            return (Criteria) this;
        }

        public Criteria andVehicletypeNotEqualTo(String value) {
            addCriterion("vehicletype <>", value, "vehicletype");
            return (Criteria) this;
        }

        public Criteria andVehicletypeGreaterThan(String value) {
            addCriterion("vehicletype >", value, "vehicletype");
            return (Criteria) this;
        }

        public Criteria andVehicletypeGreaterThanOrEqualTo(String value) {
            addCriterion("vehicletype >=", value, "vehicletype");
            return (Criteria) this;
        }

        public Criteria andVehicletypeLessThan(String value) {
            addCriterion("vehicletype <", value, "vehicletype");
            return (Criteria) this;
        }

        public Criteria andVehicletypeLessThanOrEqualTo(String value) {
            addCriterion("vehicletype <=", value, "vehicletype");
            return (Criteria) this;
        }

        public Criteria andVehicletypeLike(String value) {
            addCriterion("vehicletype like", value, "vehicletype");
            return (Criteria) this;
        }

        public Criteria andVehicletypeNotLike(String value) {
            addCriterion("vehicletype not like", value, "vehicletype");
            return (Criteria) this;
        }

        public Criteria andVehicletypeIn(List<String> values) {
            addCriterion("vehicletype in", values, "vehicletype");
            return (Criteria) this;
        }

        public Criteria andVehicletypeNotIn(List<String> values) {
            addCriterion("vehicletype not in", values, "vehicletype");
            return (Criteria) this;
        }

        public Criteria andVehicletypeBetween(String value1, String value2) {
            addCriterion("vehicletype between", value1, value2, "vehicletype");
            return (Criteria) this;
        }

        public Criteria andVehicletypeNotBetween(String value1, String value2) {
            addCriterion("vehicletype not between", value1, value2, "vehicletype");
            return (Criteria) this;
        }

        public Criteria andVehiclecolorIsNull() {
            addCriterion("vehiclecolor is null");
            return (Criteria) this;
        }

        public Criteria andVehiclecolorIsNotNull() {
            addCriterion("vehiclecolor is not null");
            return (Criteria) this;
        }

        public Criteria andVehiclecolorEqualTo(String value) {
            addCriterion("vehiclecolor =", value, "vehiclecolor");
            return (Criteria) this;
        }

        public Criteria andVehiclecolorNotEqualTo(String value) {
            addCriterion("vehiclecolor <>", value, "vehiclecolor");
            return (Criteria) this;
        }

        public Criteria andVehiclecolorGreaterThan(String value) {
            addCriterion("vehiclecolor >", value, "vehiclecolor");
            return (Criteria) this;
        }

        public Criteria andVehiclecolorGreaterThanOrEqualTo(String value) {
            addCriterion("vehiclecolor >=", value, "vehiclecolor");
            return (Criteria) this;
        }

        public Criteria andVehiclecolorLessThan(String value) {
            addCriterion("vehiclecolor <", value, "vehiclecolor");
            return (Criteria) this;
        }

        public Criteria andVehiclecolorLessThanOrEqualTo(String value) {
            addCriterion("vehiclecolor <=", value, "vehiclecolor");
            return (Criteria) this;
        }

        public Criteria andVehiclecolorLike(String value) {
            addCriterion("vehiclecolor like", value, "vehiclecolor");
            return (Criteria) this;
        }

        public Criteria andVehiclecolorNotLike(String value) {
            addCriterion("vehiclecolor not like", value, "vehiclecolor");
            return (Criteria) this;
        }

        public Criteria andVehiclecolorIn(List<String> values) {
            addCriterion("vehiclecolor in", values, "vehiclecolor");
            return (Criteria) this;
        }

        public Criteria andVehiclecolorNotIn(List<String> values) {
            addCriterion("vehiclecolor not in", values, "vehiclecolor");
            return (Criteria) this;
        }

        public Criteria andVehiclecolorBetween(String value1, String value2) {
            addCriterion("vehiclecolor between", value1, value2, "vehiclecolor");
            return (Criteria) this;
        }

        public Criteria andVehiclecolorNotBetween(String value1, String value2) {
            addCriterion("vehiclecolor not between", value1, value2, "vehiclecolor");
            return (Criteria) this;
        }

        public Criteria andVehiclestateIsNull() {
            addCriterion("vehiclestate is null");
            return (Criteria) this;
        }

        public Criteria andVehiclestateIsNotNull() {
            addCriterion("vehiclestate is not null");
            return (Criteria) this;
        }

        public Criteria andVehiclestateEqualTo(String value) {
            addCriterion("vehiclestate =", value, "vehiclestate");
            return (Criteria) this;
        }

        public Criteria andVehiclestateNotEqualTo(String value) {
            addCriterion("vehiclestate <>", value, "vehiclestate");
            return (Criteria) this;
        }

        public Criteria andVehiclestateGreaterThan(String value) {
            addCriterion("vehiclestate >", value, "vehiclestate");
            return (Criteria) this;
        }

        public Criteria andVehiclestateGreaterThanOrEqualTo(String value) {
            addCriterion("vehiclestate >=", value, "vehiclestate");
            return (Criteria) this;
        }

        public Criteria andVehiclestateLessThan(String value) {
            addCriterion("vehiclestate <", value, "vehiclestate");
            return (Criteria) this;
        }

        public Criteria andVehiclestateLessThanOrEqualTo(String value) {
            addCriterion("vehiclestate <=", value, "vehiclestate");
            return (Criteria) this;
        }

        public Criteria andVehiclestateLike(String value) {
            addCriterion("vehiclestate like", value, "vehiclestate");
            return (Criteria) this;
        }

        public Criteria andVehiclestateNotLike(String value) {
            addCriterion("vehiclestate not like", value, "vehiclestate");
            return (Criteria) this;
        }

        public Criteria andVehiclestateIn(List<String> values) {
            addCriterion("vehiclestate in", values, "vehiclestate");
            return (Criteria) this;
        }

        public Criteria andVehiclestateNotIn(List<String> values) {
            addCriterion("vehiclestate not in", values, "vehiclestate");
            return (Criteria) this;
        }

        public Criteria andVehiclestateBetween(String value1, String value2) {
            addCriterion("vehiclestate between", value1, value2, "vehiclestate");
            return (Criteria) this;
        }

        public Criteria andVehiclestateNotBetween(String value1, String value2) {
            addCriterion("vehiclestate not between", value1, value2, "vehiclestate");
            return (Criteria) this;
        }

        public Criteria andEnginenumIsNull() {
            addCriterion("enginenum is null");
            return (Criteria) this;
        }

        public Criteria andEnginenumIsNotNull() {
            addCriterion("enginenum is not null");
            return (Criteria) this;
        }

        public Criteria andEnginenumEqualTo(String value) {
            addCriterion("enginenum =", value, "enginenum");
            return (Criteria) this;
        }

        public Criteria andEnginenumNotEqualTo(String value) {
            addCriterion("enginenum <>", value, "enginenum");
            return (Criteria) this;
        }

        public Criteria andEnginenumGreaterThan(String value) {
            addCriterion("enginenum >", value, "enginenum");
            return (Criteria) this;
        }

        public Criteria andEnginenumGreaterThanOrEqualTo(String value) {
            addCriterion("enginenum >=", value, "enginenum");
            return (Criteria) this;
        }

        public Criteria andEnginenumLessThan(String value) {
            addCriterion("enginenum <", value, "enginenum");
            return (Criteria) this;
        }

        public Criteria andEnginenumLessThanOrEqualTo(String value) {
            addCriterion("enginenum <=", value, "enginenum");
            return (Criteria) this;
        }

        public Criteria andEnginenumLike(String value) {
            addCriterion("enginenum like", value, "enginenum");
            return (Criteria) this;
        }

        public Criteria andEnginenumNotLike(String value) {
            addCriterion("enginenum not like", value, "enginenum");
            return (Criteria) this;
        }

        public Criteria andEnginenumIn(List<String> values) {
            addCriterion("enginenum in", values, "enginenum");
            return (Criteria) this;
        }

        public Criteria andEnginenumNotIn(List<String> values) {
            addCriterion("enginenum not in", values, "enginenum");
            return (Criteria) this;
        }

        public Criteria andEnginenumBetween(String value1, String value2) {
            addCriterion("enginenum between", value1, value2, "enginenum");
            return (Criteria) this;
        }

        public Criteria andEnginenumNotBetween(String value1, String value2) {
            addCriterion("enginenum not between", value1, value2, "enginenum");
            return (Criteria) this;
        }

        public Criteria andOrgidIsNull() {
            addCriterion("orgid is null");
            return (Criteria) this;
        }

        public Criteria andOrgidIsNotNull() {
            addCriterion("orgid is not null");
            return (Criteria) this;
        }

        public Criteria andOrgidEqualTo(String value) {
            addCriterion("orgid =", value, "orgid");
            return (Criteria) this;
        }

        public Criteria andOrgidNotEqualTo(String value) {
            addCriterion("orgid <>", value, "orgid");
            return (Criteria) this;
        }

        public Criteria andOrgidGreaterThan(String value) {
            addCriterion("orgid >", value, "orgid");
            return (Criteria) this;
        }

        public Criteria andOrgidGreaterThanOrEqualTo(String value) {
            addCriterion("orgid >=", value, "orgid");
            return (Criteria) this;
        }

        public Criteria andOrgidLessThan(String value) {
            addCriterion("orgid <", value, "orgid");
            return (Criteria) this;
        }

        public Criteria andOrgidLessThanOrEqualTo(String value) {
            addCriterion("orgid <=", value, "orgid");
            return (Criteria) this;
        }

        public Criteria andOrgidLike(String value) {
            addCriterion("orgid like", value, "orgid");
            return (Criteria) this;
        }

        public Criteria andOrgidNotLike(String value) {
            addCriterion("orgid not like", value, "orgid");
            return (Criteria) this;
        }

        public Criteria andOrgidIn(List<String> values) {
            addCriterion("orgid in", values, "orgid");
            return (Criteria) this;
        }

        public Criteria andOrgidNotIn(List<String> values) {
            addCriterion("orgid not in", values, "orgid");
            return (Criteria) this;
        }

        public Criteria andOrgidBetween(String value1, String value2) {
            addCriterion("orgid between", value1, value2, "orgid");
            return (Criteria) this;
        }

        public Criteria andOrgidNotBetween(String value1, String value2) {
            addCriterion("orgid not between", value1, value2, "orgid");
            return (Criteria) this;
        }

        public Criteria andDriverIsNull() {
            addCriterion("driver is null");
            return (Criteria) this;
        }

        public Criteria andDriverIsNotNull() {
            addCriterion("driver is not null");
            return (Criteria) this;
        }

        public Criteria andDriverEqualTo(String value) {
            addCriterion("driver =", value, "driver");
            return (Criteria) this;
        }

        public Criteria andDriverNotEqualTo(String value) {
            addCriterion("driver <>", value, "driver");
            return (Criteria) this;
        }

        public Criteria andDriverGreaterThan(String value) {
            addCriterion("driver >", value, "driver");
            return (Criteria) this;
        }

        public Criteria andDriverGreaterThanOrEqualTo(String value) {
            addCriterion("driver >=", value, "driver");
            return (Criteria) this;
        }

        public Criteria andDriverLessThan(String value) {
            addCriterion("driver <", value, "driver");
            return (Criteria) this;
        }

        public Criteria andDriverLessThanOrEqualTo(String value) {
            addCriterion("driver <=", value, "driver");
            return (Criteria) this;
        }

        public Criteria andDriverLike(String value) {
            addCriterion("driver like", value, "driver");
            return (Criteria) this;
        }

        public Criteria andDriverNotLike(String value) {
            addCriterion("driver not like", value, "driver");
            return (Criteria) this;
        }

        public Criteria andDriverIn(List<String> values) {
            addCriterion("driver in", values, "driver");
            return (Criteria) this;
        }

        public Criteria andDriverNotIn(List<String> values) {
            addCriterion("driver not in", values, "driver");
            return (Criteria) this;
        }

        public Criteria andDriverBetween(String value1, String value2) {
            addCriterion("driver between", value1, value2, "driver");
            return (Criteria) this;
        }

        public Criteria andDriverNotBetween(String value1, String value2) {
            addCriterion("driver not between", value1, value2, "driver");
            return (Criteria) this;
        }

        public Criteria andDrivernameIsNull() {
            addCriterion("drivername is null");
            return (Criteria) this;
        }

        public Criteria andDrivernameIsNotNull() {
            addCriterion("drivername is not null");
            return (Criteria) this;
        }

        public Criteria andDrivernameEqualTo(String value) {
            addCriterion("drivername =", value, "drivername");
            return (Criteria) this;
        }

        public Criteria andDrivernameNotEqualTo(String value) {
            addCriterion("drivername <>", value, "drivername");
            return (Criteria) this;
        }

        public Criteria andDrivernameGreaterThan(String value) {
            addCriterion("drivername >", value, "drivername");
            return (Criteria) this;
        }

        public Criteria andDrivernameGreaterThanOrEqualTo(String value) {
            addCriterion("drivername >=", value, "drivername");
            return (Criteria) this;
        }

        public Criteria andDrivernameLessThan(String value) {
            addCriterion("drivername <", value, "drivername");
            return (Criteria) this;
        }

        public Criteria andDrivernameLessThanOrEqualTo(String value) {
            addCriterion("drivername <=", value, "drivername");
            return (Criteria) this;
        }

        public Criteria andDrivernameLike(String value) {
            addCriterion("drivername like", value, "drivername");
            return (Criteria) this;
        }

        public Criteria andDrivernameNotLike(String value) {
            addCriterion("drivername not like", value, "drivername");
            return (Criteria) this;
        }

        public Criteria andDrivernameIn(List<String> values) {
            addCriterion("drivername in", values, "drivername");
            return (Criteria) this;
        }

        public Criteria andDrivernameNotIn(List<String> values) {
            addCriterion("drivername not in", values, "drivername");
            return (Criteria) this;
        }

        public Criteria andDrivernameBetween(String value1, String value2) {
            addCriterion("drivername between", value1, value2, "drivername");
            return (Criteria) this;
        }

        public Criteria andDrivernameNotBetween(String value1, String value2) {
            addCriterion("drivername not between", value1, value2, "drivername");
            return (Criteria) this;
        }

        public Criteria andRegisterdateIsNull() {
            addCriterion("registerdate is null");
            return (Criteria) this;
        }

        public Criteria andRegisterdateIsNotNull() {
            addCriterion("registerdate is not null");
            return (Criteria) this;
        }

        public Criteria andRegisterdateEqualTo(Date value) {
            addCriterionForJDBCDate("registerdate =", value, "registerdate");
            return (Criteria) this;
        }

        public Criteria andRegisterdateNotEqualTo(Date value) {
            addCriterionForJDBCDate("registerdate <>", value, "registerdate");
            return (Criteria) this;
        }

        public Criteria andRegisterdateGreaterThan(Date value) {
            addCriterionForJDBCDate("registerdate >", value, "registerdate");
            return (Criteria) this;
        }

        public Criteria andRegisterdateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("registerdate >=", value, "registerdate");
            return (Criteria) this;
        }

        public Criteria andRegisterdateLessThan(Date value) {
            addCriterionForJDBCDate("registerdate <", value, "registerdate");
            return (Criteria) this;
        }

        public Criteria andRegisterdateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("registerdate <=", value, "registerdate");
            return (Criteria) this;
        }

        public Criteria andRegisterdateIn(List<Date> values) {
            addCriterionForJDBCDate("registerdate in", values, "registerdate");
            return (Criteria) this;
        }

        public Criteria andRegisterdateNotIn(List<Date> values) {
            addCriterionForJDBCDate("registerdate not in", values, "registerdate");
            return (Criteria) this;
        }

        public Criteria andRegisterdateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("registerdate between", value1, value2, "registerdate");
            return (Criteria) this;
        }

        public Criteria andRegisterdateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("registerdate not between", value1, value2, "registerdate");
            return (Criteria) this;
        }

        public Criteria andLastrepairIsNull() {
            addCriterion("lastrepair is null");
            return (Criteria) this;
        }

        public Criteria andLastrepairIsNotNull() {
            addCriterion("lastrepair is not null");
            return (Criteria) this;
        }

        public Criteria andLastrepairEqualTo(Date value) {
            addCriterionForJDBCDate("lastrepair =", value, "lastrepair");
            return (Criteria) this;
        }

        public Criteria andLastrepairNotEqualTo(Date value) {
            addCriterionForJDBCDate("lastrepair <>", value, "lastrepair");
            return (Criteria) this;
        }

        public Criteria andLastrepairGreaterThan(Date value) {
            addCriterionForJDBCDate("lastrepair >", value, "lastrepair");
            return (Criteria) this;
        }

        public Criteria andLastrepairGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("lastrepair >=", value, "lastrepair");
            return (Criteria) this;
        }

        public Criteria andLastrepairLessThan(Date value) {
            addCriterionForJDBCDate("lastrepair <", value, "lastrepair");
            return (Criteria) this;
        }

        public Criteria andLastrepairLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("lastrepair <=", value, "lastrepair");
            return (Criteria) this;
        }

        public Criteria andLastrepairIn(List<Date> values) {
            addCriterionForJDBCDate("lastrepair in", values, "lastrepair");
            return (Criteria) this;
        }

        public Criteria andLastrepairNotIn(List<Date> values) {
            addCriterionForJDBCDate("lastrepair not in", values, "lastrepair");
            return (Criteria) this;
        }

        public Criteria andLastrepairBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("lastrepair between", value1, value2, "lastrepair");
            return (Criteria) this;
        }

        public Criteria andLastrepairNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("lastrepair not between", value1, value2, "lastrepair");
            return (Criteria) this;
        }

        public Criteria andNextmaintaindateIsNull() {
            addCriterion("nextmaintaindate is null");
            return (Criteria) this;
        }

        public Criteria andNextmaintaindateIsNotNull() {
            addCriterion("nextmaintaindate is not null");
            return (Criteria) this;
        }

        public Criteria andNextmaintaindateEqualTo(Date value) {
            addCriterionForJDBCDate("nextmaintaindate =", value, "nextmaintaindate");
            return (Criteria) this;
        }

        public Criteria andNextmaintaindateNotEqualTo(Date value) {
            addCriterionForJDBCDate("nextmaintaindate <>", value, "nextmaintaindate");
            return (Criteria) this;
        }

        public Criteria andNextmaintaindateGreaterThan(Date value) {
            addCriterionForJDBCDate("nextmaintaindate >", value, "nextmaintaindate");
            return (Criteria) this;
        }

        public Criteria andNextmaintaindateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("nextmaintaindate >=", value, "nextmaintaindate");
            return (Criteria) this;
        }

        public Criteria andNextmaintaindateLessThan(Date value) {
            addCriterionForJDBCDate("nextmaintaindate <", value, "nextmaintaindate");
            return (Criteria) this;
        }

        public Criteria andNextmaintaindateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("nextmaintaindate <=", value, "nextmaintaindate");
            return (Criteria) this;
        }

        public Criteria andNextmaintaindateIn(List<Date> values) {
            addCriterionForJDBCDate("nextmaintaindate in", values, "nextmaintaindate");
            return (Criteria) this;
        }

        public Criteria andNextmaintaindateNotIn(List<Date> values) {
            addCriterionForJDBCDate("nextmaintaindate not in", values, "nextmaintaindate");
            return (Criteria) this;
        }

        public Criteria andNextmaintaindateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("nextmaintaindate between", value1, value2, "nextmaintaindate");
            return (Criteria) this;
        }

        public Criteria andNextmaintaindateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("nextmaintaindate not between", value1, value2, "nextmaintaindate");
            return (Criteria) this;
        }

        public Criteria andCycletimeIsNull() {
            addCriterion("cycletime is null");
            return (Criteria) this;
        }

        public Criteria andCycletimeIsNotNull() {
            addCriterion("cycletime is not null");
            return (Criteria) this;
        }

        public Criteria andCycletimeEqualTo(String value) {
            addCriterion("cycletime =", value, "cycletime");
            return (Criteria) this;
        }

        public Criteria andCycletimeNotEqualTo(String value) {
            addCriterion("cycletime <>", value, "cycletime");
            return (Criteria) this;
        }

        public Criteria andCycletimeGreaterThan(String value) {
            addCriterion("cycletime >", value, "cycletime");
            return (Criteria) this;
        }

        public Criteria andCycletimeGreaterThanOrEqualTo(String value) {
            addCriterion("cycletime >=", value, "cycletime");
            return (Criteria) this;
        }

        public Criteria andCycletimeLessThan(String value) {
            addCriterion("cycletime <", value, "cycletime");
            return (Criteria) this;
        }

        public Criteria andCycletimeLessThanOrEqualTo(String value) {
            addCriterion("cycletime <=", value, "cycletime");
            return (Criteria) this;
        }

        public Criteria andCycletimeLike(String value) {
            addCriterion("cycletime like", value, "cycletime");
            return (Criteria) this;
        }

        public Criteria andCycletimeNotLike(String value) {
            addCriterion("cycletime not like", value, "cycletime");
            return (Criteria) this;
        }

        public Criteria andCycletimeIn(List<String> values) {
            addCriterion("cycletime in", values, "cycletime");
            return (Criteria) this;
        }

        public Criteria andCycletimeNotIn(List<String> values) {
            addCriterion("cycletime not in", values, "cycletime");
            return (Criteria) this;
        }

        public Criteria andCycletimeBetween(String value1, String value2) {
            addCriterion("cycletime between", value1, value2, "cycletime");
            return (Criteria) this;
        }

        public Criteria andCycletimeNotBetween(String value1, String value2) {
            addCriterion("cycletime not between", value1, value2, "cycletime");
            return (Criteria) this;
        }

        public Criteria andNextcheckdateIsNull() {
            addCriterion("nextcheckdate is null");
            return (Criteria) this;
        }

        public Criteria andNextcheckdateIsNotNull() {
            addCriterion("nextcheckdate is not null");
            return (Criteria) this;
        }

        public Criteria andNextcheckdateEqualTo(Date value) {
            addCriterionForJDBCDate("nextcheckdate =", value, "nextcheckdate");
            return (Criteria) this;
        }

        public Criteria andNextcheckdateNotEqualTo(Date value) {
            addCriterionForJDBCDate("nextcheckdate <>", value, "nextcheckdate");
            return (Criteria) this;
        }

        public Criteria andNextcheckdateGreaterThan(Date value) {
            addCriterionForJDBCDate("nextcheckdate >", value, "nextcheckdate");
            return (Criteria) this;
        }

        public Criteria andNextcheckdateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("nextcheckdate >=", value, "nextcheckdate");
            return (Criteria) this;
        }

        public Criteria andNextcheckdateLessThan(Date value) {
            addCriterionForJDBCDate("nextcheckdate <", value, "nextcheckdate");
            return (Criteria) this;
        }

        public Criteria andNextcheckdateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("nextcheckdate <=", value, "nextcheckdate");
            return (Criteria) this;
        }

        public Criteria andNextcheckdateIn(List<Date> values) {
            addCriterionForJDBCDate("nextcheckdate in", values, "nextcheckdate");
            return (Criteria) this;
        }

        public Criteria andNextcheckdateNotIn(List<Date> values) {
            addCriterionForJDBCDate("nextcheckdate not in", values, "nextcheckdate");
            return (Criteria) this;
        }

        public Criteria andNextcheckdateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("nextcheckdate between", value1, value2, "nextcheckdate");
            return (Criteria) this;
        }

        public Criteria andNextcheckdateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("nextcheckdate not between", value1, value2, "nextcheckdate");
            return (Criteria) this;
        }

        public Criteria andCcycletimeIsNull() {
            addCriterion("ccycletime is null");
            return (Criteria) this;
        }

        public Criteria andCcycletimeIsNotNull() {
            addCriterion("ccycletime is not null");
            return (Criteria) this;
        }

        public Criteria andCcycletimeEqualTo(String value) {
            addCriterion("ccycletime =", value, "ccycletime");
            return (Criteria) this;
        }

        public Criteria andCcycletimeNotEqualTo(String value) {
            addCriterion("ccycletime <>", value, "ccycletime");
            return (Criteria) this;
        }

        public Criteria andCcycletimeGreaterThan(String value) {
            addCriterion("ccycletime >", value, "ccycletime");
            return (Criteria) this;
        }

        public Criteria andCcycletimeGreaterThanOrEqualTo(String value) {
            addCriterion("ccycletime >=", value, "ccycletime");
            return (Criteria) this;
        }

        public Criteria andCcycletimeLessThan(String value) {
            addCriterion("ccycletime <", value, "ccycletime");
            return (Criteria) this;
        }

        public Criteria andCcycletimeLessThanOrEqualTo(String value) {
            addCriterion("ccycletime <=", value, "ccycletime");
            return (Criteria) this;
        }

        public Criteria andCcycletimeLike(String value) {
            addCriterion("ccycletime like", value, "ccycletime");
            return (Criteria) this;
        }

        public Criteria andCcycletimeNotLike(String value) {
            addCriterion("ccycletime not like", value, "ccycletime");
            return (Criteria) this;
        }

        public Criteria andCcycletimeIn(List<String> values) {
            addCriterion("ccycletime in", values, "ccycletime");
            return (Criteria) this;
        }

        public Criteria andCcycletimeNotIn(List<String> values) {
            addCriterion("ccycletime not in", values, "ccycletime");
            return (Criteria) this;
        }

        public Criteria andCcycletimeBetween(String value1, String value2) {
            addCriterion("ccycletime between", value1, value2, "ccycletime");
            return (Criteria) this;
        }

        public Criteria andCcycletimeNotBetween(String value1, String value2) {
            addCriterion("ccycletime not between", value1, value2, "ccycletime");
            return (Criteria) this;
        }

        public Criteria andReserved1IsNull() {
            addCriterion("reserved1 is null");
            return (Criteria) this;
        }

        public Criteria andReserved1IsNotNull() {
            addCriterion("reserved1 is not null");
            return (Criteria) this;
        }

        public Criteria andReserved1EqualTo(String value) {
            addCriterion("reserved1 =", value, "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved1NotEqualTo(String value) {
            addCriterion("reserved1 <>", value, "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved1GreaterThan(String value) {
            addCriterion("reserved1 >", value, "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved1GreaterThanOrEqualTo(String value) {
            addCriterion("reserved1 >=", value, "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved1LessThan(String value) {
            addCriterion("reserved1 <", value, "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved1LessThanOrEqualTo(String value) {
            addCriterion("reserved1 <=", value, "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved1Like(String value) {
            addCriterion("reserved1 like", value, "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved1NotLike(String value) {
            addCriterion("reserved1 not like", value, "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved1In(List<String> values) {
            addCriterion("reserved1 in", values, "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved1NotIn(List<String> values) {
            addCriterion("reserved1 not in", values, "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved1Between(String value1, String value2) {
            addCriterion("reserved1 between", value1, value2, "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved1NotBetween(String value1, String value2) {
            addCriterion("reserved1 not between", value1, value2, "reserved1");
            return (Criteria) this;
        }

        public Criteria andReserved2IsNull() {
            addCriterion("reserved2 is null");
            return (Criteria) this;
        }

        public Criteria andReserved2IsNotNull() {
            addCriterion("reserved2 is not null");
            return (Criteria) this;
        }

        public Criteria andReserved2EqualTo(String value) {
            addCriterion("reserved2 =", value, "reserved2");
            return (Criteria) this;
        }

        public Criteria andReserved2NotEqualTo(String value) {
            addCriterion("reserved2 <>", value, "reserved2");
            return (Criteria) this;
        }

        public Criteria andReserved2GreaterThan(String value) {
            addCriterion("reserved2 >", value, "reserved2");
            return (Criteria) this;
        }

        public Criteria andReserved2GreaterThanOrEqualTo(String value) {
            addCriterion("reserved2 >=", value, "reserved2");
            return (Criteria) this;
        }

        public Criteria andReserved2LessThan(String value) {
            addCriterion("reserved2 <", value, "reserved2");
            return (Criteria) this;
        }

        public Criteria andReserved2LessThanOrEqualTo(String value) {
            addCriterion("reserved2 <=", value, "reserved2");
            return (Criteria) this;
        }

        public Criteria andReserved2Like(String value) {
            addCriterion("reserved2 like", value, "reserved2");
            return (Criteria) this;
        }

        public Criteria andReserved2NotLike(String value) {
            addCriterion("reserved2 not like", value, "reserved2");
            return (Criteria) this;
        }

        public Criteria andReserved2In(List<String> values) {
            addCriterion("reserved2 in", values, "reserved2");
            return (Criteria) this;
        }

        public Criteria andReserved2NotIn(List<String> values) {
            addCriterion("reserved2 not in", values, "reserved2");
            return (Criteria) this;
        }

        public Criteria andReserved2Between(String value1, String value2) {
            addCriterion("reserved2 between", value1, value2, "reserved2");
            return (Criteria) this;
        }

        public Criteria andReserved2NotBetween(String value1, String value2) {
            addCriterion("reserved2 not between", value1, value2, "reserved2");
            return (Criteria) this;
        }

        public Criteria andReserved3IsNull() {
            addCriterion("reserved3 is null");
            return (Criteria) this;
        }

        public Criteria andReserved3IsNotNull() {
            addCriterion("reserved3 is not null");
            return (Criteria) this;
        }

        public Criteria andReserved3EqualTo(String value) {
            addCriterion("reserved3 =", value, "reserved3");
            return (Criteria) this;
        }

        public Criteria andReserved3NotEqualTo(String value) {
            addCriterion("reserved3 <>", value, "reserved3");
            return (Criteria) this;
        }

        public Criteria andReserved3GreaterThan(String value) {
            addCriterion("reserved3 >", value, "reserved3");
            return (Criteria) this;
        }

        public Criteria andReserved3GreaterThanOrEqualTo(String value) {
            addCriterion("reserved3 >=", value, "reserved3");
            return (Criteria) this;
        }

        public Criteria andReserved3LessThan(String value) {
            addCriterion("reserved3 <", value, "reserved3");
            return (Criteria) this;
        }

        public Criteria andReserved3LessThanOrEqualTo(String value) {
            addCriterion("reserved3 <=", value, "reserved3");
            return (Criteria) this;
        }

        public Criteria andReserved3Like(String value) {
            addCriterion("reserved3 like", value, "reserved3");
            return (Criteria) this;
        }

        public Criteria andReserved3NotLike(String value) {
            addCriterion("reserved3 not like", value, "reserved3");
            return (Criteria) this;
        }

        public Criteria andReserved3In(List<String> values) {
            addCriterion("reserved3 in", values, "reserved3");
            return (Criteria) this;
        }

        public Criteria andReserved3NotIn(List<String> values) {
            addCriterion("reserved3 not in", values, "reserved3");
            return (Criteria) this;
        }

        public Criteria andReserved3Between(String value1, String value2) {
            addCriterion("reserved3 between", value1, value2, "reserved3");
            return (Criteria) this;
        }

        public Criteria andReserved3NotBetween(String value1, String value2) {
            addCriterion("reserved3 not between", value1, value2, "reserved3");
            return (Criteria) this;
        }

        public Criteria andReserved4IsNull() {
            addCriterion("reserved4 is null");
            return (Criteria) this;
        }

        public Criteria andReserved4IsNotNull() {
            addCriterion("reserved4 is not null");
            return (Criteria) this;
        }

        public Criteria andReserved4EqualTo(String value) {
            addCriterion("reserved4 =", value, "reserved4");
            return (Criteria) this;
        }

        public Criteria andReserved4NotEqualTo(String value) {
            addCriterion("reserved4 <>", value, "reserved4");
            return (Criteria) this;
        }

        public Criteria andReserved4GreaterThan(String value) {
            addCriterion("reserved4 >", value, "reserved4");
            return (Criteria) this;
        }

        public Criteria andReserved4GreaterThanOrEqualTo(String value) {
            addCriterion("reserved4 >=", value, "reserved4");
            return (Criteria) this;
        }

        public Criteria andReserved4LessThan(String value) {
            addCriterion("reserved4 <", value, "reserved4");
            return (Criteria) this;
        }

        public Criteria andReserved4LessThanOrEqualTo(String value) {
            addCriterion("reserved4 <=", value, "reserved4");
            return (Criteria) this;
        }

        public Criteria andReserved4Like(String value) {
            addCriterion("reserved4 like", value, "reserved4");
            return (Criteria) this;
        }

        public Criteria andReserved4NotLike(String value) {
            addCriterion("reserved4 not like", value, "reserved4");
            return (Criteria) this;
        }

        public Criteria andReserved4In(List<String> values) {
            addCriterion("reserved4 in", values, "reserved4");
            return (Criteria) this;
        }

        public Criteria andReserved4NotIn(List<String> values) {
            addCriterion("reserved4 not in", values, "reserved4");
            return (Criteria) this;
        }

        public Criteria andReserved4Between(String value1, String value2) {
            addCriterion("reserved4 between", value1, value2, "reserved4");
            return (Criteria) this;
        }

        public Criteria andReserved4NotBetween(String value1, String value2) {
            addCriterion("reserved4 not between", value1, value2, "reserved4");
            return (Criteria) this;
        }

        public Criteria andReserved5IsNull() {
            addCriterion("reserved5 is null");
            return (Criteria) this;
        }

        public Criteria andReserved5IsNotNull() {
            addCriterion("reserved5 is not null");
            return (Criteria) this;
        }

        public Criteria andReserved5EqualTo(String value) {
            addCriterion("reserved5 =", value, "reserved5");
            return (Criteria) this;
        }

        public Criteria andReserved5NotEqualTo(String value) {
            addCriterion("reserved5 <>", value, "reserved5");
            return (Criteria) this;
        }

        public Criteria andReserved5GreaterThan(String value) {
            addCriterion("reserved5 >", value, "reserved5");
            return (Criteria) this;
        }

        public Criteria andReserved5GreaterThanOrEqualTo(String value) {
            addCriterion("reserved5 >=", value, "reserved5");
            return (Criteria) this;
        }

        public Criteria andReserved5LessThan(String value) {
            addCriterion("reserved5 <", value, "reserved5");
            return (Criteria) this;
        }

        public Criteria andReserved5LessThanOrEqualTo(String value) {
            addCriterion("reserved5 <=", value, "reserved5");
            return (Criteria) this;
        }

        public Criteria andReserved5Like(String value) {
            addCriterion("reserved5 like", value, "reserved5");
            return (Criteria) this;
        }

        public Criteria andReserved5NotLike(String value) {
            addCriterion("reserved5 not like", value, "reserved5");
            return (Criteria) this;
        }

        public Criteria andReserved5In(List<String> values) {
            addCriterion("reserved5 in", values, "reserved5");
            return (Criteria) this;
        }

        public Criteria andReserved5NotIn(List<String> values) {
            addCriterion("reserved5 not in", values, "reserved5");
            return (Criteria) this;
        }

        public Criteria andReserved5Between(String value1, String value2) {
            addCriterion("reserved5 between", value1, value2, "reserved5");
            return (Criteria) this;
        }

        public Criteria andReserved5NotBetween(String value1, String value2) {
            addCriterion("reserved5 not between", value1, value2, "reserved5");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hb_vehicle
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hb_vehicle
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}