package com.example.demo.global.domain.model;

import java.math.BigDecimal;
import java.util.Date;

public class HbVehicleInsurance {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_vehicle_insurance.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_vehicle_insurance.vehicleid
     *
     * @mbg.generated
     */
    private String vehicleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_vehicle_insurance.cliamount
     *
     * @mbg.generated
     */
    private BigDecimal cliamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_vehicle_insurance.viamount
     *
     * @mbg.generated
     */
    private BigDecimal viamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_vehicle_insurance.clirenewaltime
     *
     * @mbg.generated
     */
    private Date clirenewaltime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_vehicle_insurance.virenewaltime
     *
     * @mbg.generated
     */
    private Date virenewaltime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_vehicle_insurance.cliexpdate
     *
     * @mbg.generated
     */
    private Date cliexpdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_vehicle_insurance.viexpdate
     *
     * @mbg.generated
     */
    private Date viexpdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_vehicle_insurance.insurancecycle
     *
     * @mbg.generated
     */
    private Integer insurancecycle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_vehicle_insurance.reserved1
     *
     * @mbg.generated
     */
    private String reserved1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_vehicle_insurance.reserved2
     *
     * @mbg.generated
     */
    private String reserved2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_vehicle_insurance.reserved3
     *
     * @mbg.generated
     */
    private String reserved3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_vehicle_insurance.reserved4
     *
     * @mbg.generated
     */
    private String reserved4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_vehicle_insurance.reserved5
     *
     * @mbg.generated
     */
    private String reserved5;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_vehicle_insurance.id
     *
     * @return the value of hb_vehicle_insurance.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_vehicle_insurance.id
     *
     * @param id the value for hb_vehicle_insurance.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_vehicle_insurance.vehicleid
     *
     * @return the value of hb_vehicle_insurance.vehicleid
     *
     * @mbg.generated
     */
    public String getVehicleid() {
        return vehicleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_vehicle_insurance.vehicleid
     *
     * @param vehicleid the value for hb_vehicle_insurance.vehicleid
     *
     * @mbg.generated
     */
    public void setVehicleid(String vehicleid) {
        this.vehicleid = vehicleid == null ? null : vehicleid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_vehicle_insurance.cliamount
     *
     * @return the value of hb_vehicle_insurance.cliamount
     *
     * @mbg.generated
     */
    public BigDecimal getCliamount() {
        return cliamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_vehicle_insurance.cliamount
     *
     * @param cliamount the value for hb_vehicle_insurance.cliamount
     *
     * @mbg.generated
     */
    public void setCliamount(BigDecimal cliamount) {
        this.cliamount = cliamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_vehicle_insurance.viamount
     *
     * @return the value of hb_vehicle_insurance.viamount
     *
     * @mbg.generated
     */
    public BigDecimal getViamount() {
        return viamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_vehicle_insurance.viamount
     *
     * @param viamount the value for hb_vehicle_insurance.viamount
     *
     * @mbg.generated
     */
    public void setViamount(BigDecimal viamount) {
        this.viamount = viamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_vehicle_insurance.clirenewaltime
     *
     * @return the value of hb_vehicle_insurance.clirenewaltime
     *
     * @mbg.generated
     */
    public Date getClirenewaltime() {
        return clirenewaltime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_vehicle_insurance.clirenewaltime
     *
     * @param clirenewaltime the value for hb_vehicle_insurance.clirenewaltime
     *
     * @mbg.generated
     */
    public void setClirenewaltime(Date clirenewaltime) {
        this.clirenewaltime = clirenewaltime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_vehicle_insurance.virenewaltime
     *
     * @return the value of hb_vehicle_insurance.virenewaltime
     *
     * @mbg.generated
     */
    public Date getVirenewaltime() {
        return virenewaltime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_vehicle_insurance.virenewaltime
     *
     * @param virenewaltime the value for hb_vehicle_insurance.virenewaltime
     *
     * @mbg.generated
     */
    public void setVirenewaltime(Date virenewaltime) {
        this.virenewaltime = virenewaltime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_vehicle_insurance.cliexpdate
     *
     * @return the value of hb_vehicle_insurance.cliexpdate
     *
     * @mbg.generated
     */
    public Date getCliexpdate() {
        return cliexpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_vehicle_insurance.cliexpdate
     *
     * @param cliexpdate the value for hb_vehicle_insurance.cliexpdate
     *
     * @mbg.generated
     */
    public void setCliexpdate(Date cliexpdate) {
        this.cliexpdate = cliexpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_vehicle_insurance.viexpdate
     *
     * @return the value of hb_vehicle_insurance.viexpdate
     *
     * @mbg.generated
     */
    public Date getViexpdate() {
        return viexpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_vehicle_insurance.viexpdate
     *
     * @param viexpdate the value for hb_vehicle_insurance.viexpdate
     *
     * @mbg.generated
     */
    public void setViexpdate(Date viexpdate) {
        this.viexpdate = viexpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_vehicle_insurance.insurancecycle
     *
     * @return the value of hb_vehicle_insurance.insurancecycle
     *
     * @mbg.generated
     */
    public Integer getInsurancecycle() {
        return insurancecycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_vehicle_insurance.insurancecycle
     *
     * @param insurancecycle the value for hb_vehicle_insurance.insurancecycle
     *
     * @mbg.generated
     */
    public void setInsurancecycle(Integer insurancecycle) {
        this.insurancecycle = insurancecycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_vehicle_insurance.reserved1
     *
     * @return the value of hb_vehicle_insurance.reserved1
     *
     * @mbg.generated
     */
    public String getReserved1() {
        return reserved1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_vehicle_insurance.reserved1
     *
     * @param reserved1 the value for hb_vehicle_insurance.reserved1
     *
     * @mbg.generated
     */
    public void setReserved1(String reserved1) {
        this.reserved1 = reserved1 == null ? null : reserved1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_vehicle_insurance.reserved2
     *
     * @return the value of hb_vehicle_insurance.reserved2
     *
     * @mbg.generated
     */
    public String getReserved2() {
        return reserved2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_vehicle_insurance.reserved2
     *
     * @param reserved2 the value for hb_vehicle_insurance.reserved2
     *
     * @mbg.generated
     */
    public void setReserved2(String reserved2) {
        this.reserved2 = reserved2 == null ? null : reserved2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_vehicle_insurance.reserved3
     *
     * @return the value of hb_vehicle_insurance.reserved3
     *
     * @mbg.generated
     */
    public String getReserved3() {
        return reserved3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_vehicle_insurance.reserved3
     *
     * @param reserved3 the value for hb_vehicle_insurance.reserved3
     *
     * @mbg.generated
     */
    public void setReserved3(String reserved3) {
        this.reserved3 = reserved3 == null ? null : reserved3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_vehicle_insurance.reserved4
     *
     * @return the value of hb_vehicle_insurance.reserved4
     *
     * @mbg.generated
     */
    public String getReserved4() {
        return reserved4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_vehicle_insurance.reserved4
     *
     * @param reserved4 the value for hb_vehicle_insurance.reserved4
     *
     * @mbg.generated
     */
    public void setReserved4(String reserved4) {
        this.reserved4 = reserved4 == null ? null : reserved4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_vehicle_insurance.reserved5
     *
     * @return the value of hb_vehicle_insurance.reserved5
     *
     * @mbg.generated
     */
    public String getReserved5() {
        return reserved5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_vehicle_insurance.reserved5
     *
     * @param reserved5 the value for hb_vehicle_insurance.reserved5
     *
     * @mbg.generated
     */
    public void setReserved5(String reserved5) {
        this.reserved5 = reserved5 == null ? null : reserved5.trim();
    }
}