package com.example.demo.global.domain.model;

import java.util.Date;

public class HbVehicleApp {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_vehicle_app.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_vehicle_app.applicant
     *
     * @mbg.generated
     */
    private String applicant;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_vehicle_app.apptime
     *
     * @mbg.generated
     */
    private Date apptime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_vehicle_app.usingtime
     *
     * @mbg.generated
     */
    private Date usingtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_vehicle_app.vehicletype
     *
     * @mbg.generated
     */
    private String vehicletype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_vehicle_app.orgid
     *
     * @mbg.generated
     */
    private String orgid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_vehicle_app.orgname
     *
     * @mbg.generated
     */
    private String orgname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_vehicle_app.omileage
     *
     * @mbg.generated
     */
    private Integer omileage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_vehicle_app.imileage
     *
     * @mbg.generated
     */
    private Integer imileage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_vehicle_app.vehicleno
     *
     * @mbg.generated
     */
    private String vehicleno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_vehicle_app.vehicleid
     *
     * @mbg.generated
     */
    private String vehicleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_vehicle_app.reason
     *
     * @mbg.generated
     */
    private String reason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_vehicle_app.auditflow
     *
     * @mbg.generated
     */
    private String auditflow;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_vehicle_app.auditstate
     *
     * @mbg.generated
     */
    private String auditstate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_vehicle_app.reserved1
     *
     * @mbg.generated
     */
    private String reserved1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_vehicle_app.reserved2
     *
     * @mbg.generated
     */
    private String reserved2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_vehicle_app.reserved3
     *
     * @mbg.generated
     */
    private String reserved3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_vehicle_app.reserved4
     *
     * @mbg.generated
     */
    private String reserved4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_vehicle_app.reserved5
     *
     * @mbg.generated
     */
    private String reserved5;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_vehicle_app.id
     *
     * @return the value of hb_vehicle_app.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_vehicle_app.id
     *
     * @param id the value for hb_vehicle_app.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_vehicle_app.applicant
     *
     * @return the value of hb_vehicle_app.applicant
     *
     * @mbg.generated
     */
    public String getApplicant() {
        return applicant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_vehicle_app.applicant
     *
     * @param applicant the value for hb_vehicle_app.applicant
     *
     * @mbg.generated
     */
    public void setApplicant(String applicant) {
        this.applicant = applicant == null ? null : applicant.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_vehicle_app.apptime
     *
     * @return the value of hb_vehicle_app.apptime
     *
     * @mbg.generated
     */
    public Date getApptime() {
        return apptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_vehicle_app.apptime
     *
     * @param apptime the value for hb_vehicle_app.apptime
     *
     * @mbg.generated
     */
    public void setApptime(Date apptime) {
        this.apptime = apptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_vehicle_app.usingtime
     *
     * @return the value of hb_vehicle_app.usingtime
     *
     * @mbg.generated
     */
    public Date getUsingtime() {
        return usingtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_vehicle_app.usingtime
     *
     * @param usingtime the value for hb_vehicle_app.usingtime
     *
     * @mbg.generated
     */
    public void setUsingtime(Date usingtime) {
        this.usingtime = usingtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_vehicle_app.vehicletype
     *
     * @return the value of hb_vehicle_app.vehicletype
     *
     * @mbg.generated
     */
    public String getVehicletype() {
        return vehicletype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_vehicle_app.vehicletype
     *
     * @param vehicletype the value for hb_vehicle_app.vehicletype
     *
     * @mbg.generated
     */
    public void setVehicletype(String vehicletype) {
        this.vehicletype = vehicletype == null ? null : vehicletype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_vehicle_app.orgid
     *
     * @return the value of hb_vehicle_app.orgid
     *
     * @mbg.generated
     */
    public String getOrgid() {
        return orgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_vehicle_app.orgid
     *
     * @param orgid the value for hb_vehicle_app.orgid
     *
     * @mbg.generated
     */
    public void setOrgid(String orgid) {
        this.orgid = orgid == null ? null : orgid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_vehicle_app.orgname
     *
     * @return the value of hb_vehicle_app.orgname
     *
     * @mbg.generated
     */
    public String getOrgname() {
        return orgname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_vehicle_app.orgname
     *
     * @param orgname the value for hb_vehicle_app.orgname
     *
     * @mbg.generated
     */
    public void setOrgname(String orgname) {
        this.orgname = orgname == null ? null : orgname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_vehicle_app.omileage
     *
     * @return the value of hb_vehicle_app.omileage
     *
     * @mbg.generated
     */
    public Integer getOmileage() {
        return omileage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_vehicle_app.omileage
     *
     * @param omileage the value for hb_vehicle_app.omileage
     *
     * @mbg.generated
     */
    public void setOmileage(Integer omileage) {
        this.omileage = omileage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_vehicle_app.imileage
     *
     * @return the value of hb_vehicle_app.imileage
     *
     * @mbg.generated
     */
    public Integer getImileage() {
        return imileage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_vehicle_app.imileage
     *
     * @param imileage the value for hb_vehicle_app.imileage
     *
     * @mbg.generated
     */
    public void setImileage(Integer imileage) {
        this.imileage = imileage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_vehicle_app.vehicleno
     *
     * @return the value of hb_vehicle_app.vehicleno
     *
     * @mbg.generated
     */
    public String getVehicleno() {
        return vehicleno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_vehicle_app.vehicleno
     *
     * @param vehicleno the value for hb_vehicle_app.vehicleno
     *
     * @mbg.generated
     */
    public void setVehicleno(String vehicleno) {
        this.vehicleno = vehicleno == null ? null : vehicleno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_vehicle_app.vehicleid
     *
     * @return the value of hb_vehicle_app.vehicleid
     *
     * @mbg.generated
     */
    public String getVehicleid() {
        return vehicleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_vehicle_app.vehicleid
     *
     * @param vehicleid the value for hb_vehicle_app.vehicleid
     *
     * @mbg.generated
     */
    public void setVehicleid(String vehicleid) {
        this.vehicleid = vehicleid == null ? null : vehicleid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_vehicle_app.reason
     *
     * @return the value of hb_vehicle_app.reason
     *
     * @mbg.generated
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_vehicle_app.reason
     *
     * @param reason the value for hb_vehicle_app.reason
     *
     * @mbg.generated
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_vehicle_app.auditflow
     *
     * @return the value of hb_vehicle_app.auditflow
     *
     * @mbg.generated
     */
    public String getAuditflow() {
        return auditflow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_vehicle_app.auditflow
     *
     * @param auditflow the value for hb_vehicle_app.auditflow
     *
     * @mbg.generated
     */
    public void setAuditflow(String auditflow) {
        this.auditflow = auditflow == null ? null : auditflow.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_vehicle_app.auditstate
     *
     * @return the value of hb_vehicle_app.auditstate
     *
     * @mbg.generated
     */
    public String getAuditstate() {
        return auditstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_vehicle_app.auditstate
     *
     * @param auditstate the value for hb_vehicle_app.auditstate
     *
     * @mbg.generated
     */
    public void setAuditstate(String auditstate) {
        this.auditstate = auditstate == null ? null : auditstate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_vehicle_app.reserved1
     *
     * @return the value of hb_vehicle_app.reserved1
     *
     * @mbg.generated
     */
    public String getReserved1() {
        return reserved1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_vehicle_app.reserved1
     *
     * @param reserved1 the value for hb_vehicle_app.reserved1
     *
     * @mbg.generated
     */
    public void setReserved1(String reserved1) {
        this.reserved1 = reserved1 == null ? null : reserved1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_vehicle_app.reserved2
     *
     * @return the value of hb_vehicle_app.reserved2
     *
     * @mbg.generated
     */
    public String getReserved2() {
        return reserved2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_vehicle_app.reserved2
     *
     * @param reserved2 the value for hb_vehicle_app.reserved2
     *
     * @mbg.generated
     */
    public void setReserved2(String reserved2) {
        this.reserved2 = reserved2 == null ? null : reserved2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_vehicle_app.reserved3
     *
     * @return the value of hb_vehicle_app.reserved3
     *
     * @mbg.generated
     */
    public String getReserved3() {
        return reserved3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_vehicle_app.reserved3
     *
     * @param reserved3 the value for hb_vehicle_app.reserved3
     *
     * @mbg.generated
     */
    public void setReserved3(String reserved3) {
        this.reserved3 = reserved3 == null ? null : reserved3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_vehicle_app.reserved4
     *
     * @return the value of hb_vehicle_app.reserved4
     *
     * @mbg.generated
     */
    public String getReserved4() {
        return reserved4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_vehicle_app.reserved4
     *
     * @param reserved4 the value for hb_vehicle_app.reserved4
     *
     * @mbg.generated
     */
    public void setReserved4(String reserved4) {
        this.reserved4 = reserved4 == null ? null : reserved4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_vehicle_app.reserved5
     *
     * @return the value of hb_vehicle_app.reserved5
     *
     * @mbg.generated
     */
    public String getReserved5() {
        return reserved5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_vehicle_app.reserved5
     *
     * @param reserved5 the value for hb_vehicle_app.reserved5
     *
     * @mbg.generated
     */
    public void setReserved5(String reserved5) {
        this.reserved5 = reserved5 == null ? null : reserved5.trim();
    }
}