package com.example.demo.global.domain.model;

import java.util.Date;

public class HbWarning {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_warning.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_warning.warnstring
     *
     * @mbg.generated
     */
    private String warnstring;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_warning.createtime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_warning.dealtime
     *
     * @mbg.generated
     */
    private Date dealtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_warning.dealstate
     *
     * @mbg.generated
     */
    private String dealstate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_warning.comment
     *
     * @mbg.generated
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_warning.dealtype
     *
     * @mbg.generated
     */
    private String dealtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_warning.dealuserid
     *
     * @mbg.generated
     */
    private String dealuserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_warning.orgid
     *
     * @mbg.generated
     */
    private String orgid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_warning.orgname
     *
     * @mbg.generated
     */
    private String orgname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_warning.warnlevel
     *
     * @mbg.generated
     */
    private String warnlevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_warning.warntype
     *
     * @mbg.generated
     */
    private String warntype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_warning.reserved1
     *
     * @mbg.generated
     */
    private String reserved1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_warning.reserved2
     *
     * @mbg.generated
     */
    private String reserved2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_warning.reserved3
     *
     * @mbg.generated
     */
    private String reserved3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_warning.reserved4
     *
     * @mbg.generated
     */
    private String reserved4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hb_warning.reserved5
     *
     * @mbg.generated
     */
    private String reserved5;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_warning.id
     *
     * @return the value of hb_warning.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_warning.id
     *
     * @param id the value for hb_warning.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_warning.warnstring
     *
     * @return the value of hb_warning.warnstring
     *
     * @mbg.generated
     */
    public String getWarnstring() {
        return warnstring;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_warning.warnstring
     *
     * @param warnstring the value for hb_warning.warnstring
     *
     * @mbg.generated
     */
    public void setWarnstring(String warnstring) {
        this.warnstring = warnstring == null ? null : warnstring.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_warning.createtime
     *
     * @return the value of hb_warning.createtime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_warning.createtime
     *
     * @param createtime the value for hb_warning.createtime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_warning.dealtime
     *
     * @return the value of hb_warning.dealtime
     *
     * @mbg.generated
     */
    public Date getDealtime() {
        return dealtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_warning.dealtime
     *
     * @param dealtime the value for hb_warning.dealtime
     *
     * @mbg.generated
     */
    public void setDealtime(Date dealtime) {
        this.dealtime = dealtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_warning.dealstate
     *
     * @return the value of hb_warning.dealstate
     *
     * @mbg.generated
     */
    public String getDealstate() {
        return dealstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_warning.dealstate
     *
     * @param dealstate the value for hb_warning.dealstate
     *
     * @mbg.generated
     */
    public void setDealstate(String dealstate) {
        this.dealstate = dealstate == null ? null : dealstate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_warning.comment
     *
     * @return the value of hb_warning.comment
     *
     * @mbg.generated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_warning.comment
     *
     * @param comment the value for hb_warning.comment
     *
     * @mbg.generated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_warning.dealtype
     *
     * @return the value of hb_warning.dealtype
     *
     * @mbg.generated
     */
    public String getDealtype() {
        return dealtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_warning.dealtype
     *
     * @param dealtype the value for hb_warning.dealtype
     *
     * @mbg.generated
     */
    public void setDealtype(String dealtype) {
        this.dealtype = dealtype == null ? null : dealtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_warning.dealuserid
     *
     * @return the value of hb_warning.dealuserid
     *
     * @mbg.generated
     */
    public String getDealuserid() {
        return dealuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_warning.dealuserid
     *
     * @param dealuserid the value for hb_warning.dealuserid
     *
     * @mbg.generated
     */
    public void setDealuserid(String dealuserid) {
        this.dealuserid = dealuserid == null ? null : dealuserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_warning.orgid
     *
     * @return the value of hb_warning.orgid
     *
     * @mbg.generated
     */
    public String getOrgid() {
        return orgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_warning.orgid
     *
     * @param orgid the value for hb_warning.orgid
     *
     * @mbg.generated
     */
    public void setOrgid(String orgid) {
        this.orgid = orgid == null ? null : orgid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_warning.orgname
     *
     * @return the value of hb_warning.orgname
     *
     * @mbg.generated
     */
    public String getOrgname() {
        return orgname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_warning.orgname
     *
     * @param orgname the value for hb_warning.orgname
     *
     * @mbg.generated
     */
    public void setOrgname(String orgname) {
        this.orgname = orgname == null ? null : orgname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_warning.warnlevel
     *
     * @return the value of hb_warning.warnlevel
     *
     * @mbg.generated
     */
    public String getWarnlevel() {
        return warnlevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_warning.warnlevel
     *
     * @param warnlevel the value for hb_warning.warnlevel
     *
     * @mbg.generated
     */
    public void setWarnlevel(String warnlevel) {
        this.warnlevel = warnlevel == null ? null : warnlevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_warning.warntype
     *
     * @return the value of hb_warning.warntype
     *
     * @mbg.generated
     */
    public String getWarntype() {
        return warntype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_warning.warntype
     *
     * @param warntype the value for hb_warning.warntype
     *
     * @mbg.generated
     */
    public void setWarntype(String warntype) {
        this.warntype = warntype == null ? null : warntype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_warning.reserved1
     *
     * @return the value of hb_warning.reserved1
     *
     * @mbg.generated
     */
    public String getReserved1() {
        return reserved1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_warning.reserved1
     *
     * @param reserved1 the value for hb_warning.reserved1
     *
     * @mbg.generated
     */
    public void setReserved1(String reserved1) {
        this.reserved1 = reserved1 == null ? null : reserved1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_warning.reserved2
     *
     * @return the value of hb_warning.reserved2
     *
     * @mbg.generated
     */
    public String getReserved2() {
        return reserved2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_warning.reserved2
     *
     * @param reserved2 the value for hb_warning.reserved2
     *
     * @mbg.generated
     */
    public void setReserved2(String reserved2) {
        this.reserved2 = reserved2 == null ? null : reserved2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_warning.reserved3
     *
     * @return the value of hb_warning.reserved3
     *
     * @mbg.generated
     */
    public String getReserved3() {
        return reserved3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_warning.reserved3
     *
     * @param reserved3 the value for hb_warning.reserved3
     *
     * @mbg.generated
     */
    public void setReserved3(String reserved3) {
        this.reserved3 = reserved3 == null ? null : reserved3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_warning.reserved4
     *
     * @return the value of hb_warning.reserved4
     *
     * @mbg.generated
     */
    public String getReserved4() {
        return reserved4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_warning.reserved4
     *
     * @param reserved4 the value for hb_warning.reserved4
     *
     * @mbg.generated
     */
    public void setReserved4(String reserved4) {
        this.reserved4 = reserved4 == null ? null : reserved4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hb_warning.reserved5
     *
     * @return the value of hb_warning.reserved5
     *
     * @mbg.generated
     */
    public String getReserved5() {
        return reserved5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hb_warning.reserved5
     *
     * @param reserved5 the value for hb_warning.reserved5
     *
     * @mbg.generated
     */
    public void setReserved5(String reserved5) {
        this.reserved5 = reserved5 == null ? null : reserved5.trim();
    }
}